caldera_criticalmass_getridelocation:
    pattern: /mapapi/getridelocation/{citySlug}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Api:ridelocation }

caldera_criticalmass_getcitylocation:
    pattern: /mapapi/getcitylocation/{citySlug}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Api:citylocation }

caldera_criticalmass_getcitylocationbyid:
    pattern: /mapapi/getcitylocationbyid/{cityId}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Api:citylocationbyid }

caldera_criticalmass_apilistcities:
    pattern: /api/listcities
    defaults: { _controller: CalderaCriticalmassCoreBundle:Api:listcities }