services:
    sonata.admin.ride:
        class: Caldera\CriticalmassCoreBundle\Admin\RideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Ride" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\Ride
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassCoreBundle]]

    sonata.admin.city:
        class: Caldera\CriticalmassCoreBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "City" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\City
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassCoreBundle]]

    sonata.admin.cityslug:
        class: Caldera\CriticalmassCoreBundle\Admin\CitySlugAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "CitySlug" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\CitySlug
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassCoreBundle]]

    sonata.admin.comment:
        class: Caldera\CriticalmassCoreBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comments" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\Comment
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassCoreBundle]]

    sonata.admin.tilelayer:
        class: Caldera\CriticalmassCoreBundle\Admin\TileLayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "TileLayer" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\TileLayer
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassCoreBundle]]