services:
    sonata.admin.ride:
        class: Caldera\CriticalmassAdminBundle\Admin\RideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Ride" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\Ride
            - ~
        calls:
            - [ setTranslationDomain, [CalderaCriticalmassAdminBundle]]

    sonata.admin.city:
        class: Caldera\CriticalmassAdminBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "City" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\City
            - ~
        calls:
            - [ setTranslationDomain, [CalderaCriticalmassAdminBundle]]

    sonata.admin.cityslug:
        class: Caldera\CriticalmassAdminBundle\Admin\CitySlugAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "CitySlug" }
        arguments:
            - ~
            - Caldera\CriticalmassCoreBundle\Entity\CitySlug
            - ~
        calls:
            - [ setTranslationDomain, [CalderaCriticalmassAdminBundle]]