CalderaCriticalmassCoreBundle_Api:
    resource: "@CalderaCriticalmassCoreBundle/Resources/config/routing/api.yml"
    prefix:   /

caldera_criticalmass_standardridegenerator:
    pattern: /standardridegenerator
    defaults: { _controller: CalderaCriticalmassCoreBundle:Default:index }

caldera_criticalmass_ridecompiler:
    pattern: /ridecompiler
    defaults: { _controller: CalderaCriticalmassCoreBundle:Default:index2 }

