parameters:

services:
    caldera_criticalmass_ride_repository:
        class:           Caldera\CriticalmassCoreBundle\Entity\RideRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [CalderaCriticalmassCoreBundle:Ride]