caldera_criticalmass_blog_list:
    path:     /blog/list
    defaults: { _controller: CalderaCriticalmassCoreBundle:Blog:list }

caldera_criticalmass_blog_show:
    path:     /blog/{slug}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Blog:list }
