caldera_criticalmass_board_overview:
    path:  /boards/overview
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:overview }

caldera_criticalmass_board_listthreads:
    path:  /boards/{boardSlug}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:listthreads }

caldera_criticalmass_board_addthread:
    path:  /boards/{boardSlug}/addthread
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:addthread }

caldera_criticalmass_board_viewthread:
    path:  /boards/{boardSlug}/thread/{threadSlug}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:viewthread }

caldera_criticalmass_board_listcitythreads:
    path:  /{citySlug}/listthreads
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:listthreads }

caldera_criticalmass_board_addcitythread:
    path:  /{citySlug}/addthread
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:addthread }

caldera_criticalmass_board_viewcitythread:
    path:  /{citySlug}/thread/{threadSlug}
    defaults: { _controller: CalderaCriticalmassCoreBundle:Board:viewthread }
