caldera_criticalmass_desktop_subride_add:
    path:  /{citySlug}/{rideDate}/addsubride
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:add }

caldera_criticalmass_desktop_subride_edit:
    path:  /{citySlug}/{rideDate}/editsubride/{subrideId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:edit }
    
caldera_criticalmass_subride_preparecopy:
    path:  /{citySlug}/{rideDate}/preparecopysubrides
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:preparecopy }
    
caldera_criticalmass_desktop_subride_copy:
    path:  /{citySlug}/{newDate}/copysubrides/{oldDate}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:copy }