caldera_criticalmass_timelapse_homepage:
    path:     /{citySlug}/{rideDate}/timelapse
    defaults: { _controller: CalderaCriticalmassSiteBundle:Timelapse:show }

caldera_criticalmass_timelapse_load:
    path:     /{citySlug}/{rideDate}/timelapse/load/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Timelapse:loadtrack }
    options:
        expose: true