# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [ CalderaCriticalmassSiteBundle, CalderaCyclewaysBundle ]

    filters:
        cssrewrite: ~
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

    assets:
        criticalmass_css:
            inputs:
                - bundles/calderacriticalmasssite/css/criticalmass.css
            output: css/criticalmass.css