imports:
    - { resource: parameters.yml }
    - { resource: criticalmass.yml }
    - { resource: security.yml }
    
    - { resource: assetic.yml }
    - { resource: doctrine.yml }
    - { resource: fos.yml }
    - { resource: framework.yml }
    - { resource: sonata.yml }
    - { resource: swiftmailer.yml }
    - { resource: twig.yml }
    - { resource: vich.yml }
    
    - { resource: imagesizes.yml }