imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    
    - { resource: assetic.yml }
    - { resource: doctrine.yml }
    - { resource: fos.yml }
    - { resource: framework.yml }
    - { resource: sonata.yml }
    - { resource: jms.yml }
    - { resource: swiftmailer.yml }
    - { resource: twig.yml }
    - { resource: vich.yml }
    - { resource: liip.yml }
    - { resource: knp.yml }
    - { resource: elastic.yml }
    - { resource: translation.yml }
    - { resource: memcache.yml }

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_name: main

    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebookId
            strava: stravaId
            runkeeper: runkeeperId

    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook.client_id%
            client_secret:       %facebook.secret%
        strava:
            type:                strava
            client_id:           %strava.client_id%
            client_secret:       %strava.secret%
        runkeeper:
            type:                runkeeper
            client_id:           %runkeeper.client_id%
            client_secret:       %runkeeper.secret%