doctrine:
    dbal:
        driver:   pdo_mysql
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            datetime: Caldera\Bundle\CalderaBundle\DBAL\Type\UTCDateTimeType
            date: Caldera\Bundle\CalderaBundle\DBAL\Type\UTCDateType
            time: Caldera\Bundle\CalderaBundle\DBAL\Type\UTCTimeType
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            datetime_functions:
                date: Caldera\Bundle\CriticalmassCoreBundle\DQL\DateFunction
                month: Caldera\Bundle\CriticalmassCoreBundle\DQL\MonthFunction
                year: Caldera\Bundle\CriticalmassCoreBundle\DQL\YearFunction
                dayofweek: Caldera\Bundle\CriticalmassCoreBundle\DQL\DayOfWeekFunction
            numeric_functions:
                rand: Caldera\Bundle\CriticalmassCoreBundle\DQL\RandFunction
