fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        criticalmass:
            client: default
            finder:
            types:
                article:
                    mappings:
                        title: ~
                        abstract: ~
                        text: ~
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CriticalmassModelBundle\Entity\Article
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                ride:
                    mappings:
                        title: ~
                        description: ~
                        location: ~
                        isArchived: ~
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CriticalmassModelBundle\Entity\Ride
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                city:
                    mappings:
                        title: ~
                        description: ~
                        longDescription: ~
                        punchLine: ~
                        standardLocation: ~
                        isArchived: ~
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CriticalmassModelBundle\Entity\City
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~