fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        criticalmass:
            client: default
            finder:
            types:
                content:
                    mappings:
                        id: ~
                        title: ~
                        text: ~
                        isArchived: ~
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CalderaBundle\Entity\Content
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                ride:
                    mappings:
                        id: ~
                        title: ~
                        description: ~
                        location: ~
                        isArchived: ~
                        dateTime: ~
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CalderaBundle\Entity\Ride
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                city:
                    mappings:
                        id: ~
                        title: ~
                        description: ~
                        longDescription: ~
                        punchLine: ~
                        standardLocation: ~
                        isArchived: ~
                        isEnabled: ~
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CalderaBundle\Entity\City
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
