framework:
    #esi:             ~
    translator:      { fallback: '%locale%' }
    secret:          '%kernel.secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection:
        enabled: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_proxies: ~
    session:         ~
    fragments:       ~