liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        gallery_photo_thumb:
            quality: 60
            filters:
                thumbnail: { size: [200, 150], mode: inset }
        gallery_photo_standard:
            quality: 60
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
        city_image_wide:
            quality: 60
            filters:
                thumbnail: { size: [1140, 250], mode: inset }