sonata_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

sonata_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

caldera_criticalmass:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing.yml"
    host: "%domain.criticalmass%"
    prefix:   /


