caldera_criticalmass_glympse:
    resource: "@CalderaCriticalmassGlympseBundle/Resources/config/routing.yml"
    prefix:   /

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile

sonata_user_profile_show:
    pattern: /
    defaults: { _controller: CalderaCriticalmassMobileBundle:MultiPage:main }


sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

caldera_criticalmass_core:
    resource: "@CalderaCriticalmassCoreBundle/Resources/config/routing.yml"
    prefix:   /

caldera_criticalmass_mobile:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing.yml"
    prefix:   /

caldera_criticalmass_statistic:
    resource: "@CalderaCriticalmassStatisticBundle/Resources/config/routing.yml"
    prefix:   /

caldera_criticalmass_content:
    resource: "@CalderaCriticalmassContentBundle/Resources/config/routing.yml"
    prefix:   /

caldera_criticalmass_plus:
    resource: "@CalderaCriticalmassPlusBundle/Resources/config/routing.yml"
    prefix:   /

caldera_criticalmass_heatmap:
    resource: "@CalderaCriticalmassHeatmapBundle/Resources/config/routing.yml"
    prefix:   /

caldera_criticalmass_api:
    resource: "@CalderaCriticalmassApiBundle/Resources/config/routing.yml"
    prefix:   /