fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        criticalmass_help_category:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                help_category:
                    properties:
                        id: ~
                        title: ~
                        intro: ~
                    persistence:
                        driver: orm
                        model: App\Entity\HelpCategory
                        provider: ~
                        listener: ~
                        finder: ~

        criticalmass_help_item:
                    client: default
                    finder:
                    settings:
                        index:
                            analysis:
                                analyzer:
                                    umlauts_analyzer:
                                        type: custom
                                        tokenizer: lowercase
                                        filter   : [umlauts_filter]
                                filter:
                                    umlauts_filter:
                                        type: "asciifolding"
                    types:
                        help_item:
                            properties:
                                id: ~
                                title: ~
                                text: ~
                            persistence:
                                driver: orm
                                model: App\Entity\HelpItem
                                provider: ~
                                listener: ~
                                finder: ~

        criticalmass_ride:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                ride:
                    properties:
                        id: ~
                        title: ~
                        description: ~
                        city: { type: keyword }
                        country: { type: keyword }
                        region: { type: keyword }
                        location: ~
                        isEnabled: ~
                        dateTime: { type: date, format: "strict_date_optional_time" }
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: App\Entity\Ride
                        provider: ~
                        listener: ~
                        finder: ~

        criticalmass_city:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter: [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                city:
                    properties:
                        id: ~
                        city: ~
                        title: ~
                        description: ~
                        longDescription: ~
                        punchLine: ~
                        isEnabled: ~
                        createdAt: { type: date, format: "yyyy-MM-dd" }
                        updatedAt: { type: date, format: "yyyy-MM-dd" }
                        country: { type: keyword }
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: App\Entity\City
                        provider: ~
                        listener: ~
                        finder: ~

        criticalmass_blog_post:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                blog_post:
                    properties:
                        id: ~
                        title: ~
                        intro: ~
                        text: ~
                        enabled: ~
                        createdAt: ~
                    persistence:
                        driver: orm
                        model: App\Entity\BlogPost
                        provider: ~
                        listener: ~
                        finder: ~

        criticalmass_photo:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter: [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                photo:
                    properties:
                        id: ~
                        description: ~
                        city: { type: keyword }
                        ride: { type: keyword }
                        #region: { type: keyword }
                        location: ~
                        latitude: ~
                        longitude: ~
                        enabled: ~
                        deleted: ~
                        exifExposure: ~
                        exifFocalLength: ~
                        exifAperture: ~
                        exifIso: ~
                        exifCamera: ~
                        exifCreationDate: ~
                        creationDateTime: { type: date, format: "strict_date_optional_time" }
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: App\Entity\Photo
                        provider: ~
                        listener: ~
                        finder: ~