fos_rest:
    view:
        formats:
            json: true
            xml: false
            html: false
            rss: false
        templating_formats:
            json: false
            xml: false
            html: false
            rss: false
        force_redirects:
            html: false
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    service:
        serializer: fos_rest.serializer.jms
    serializer:
        groups:               []
        serialize_null:       true
