twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        standard:
            toolbar: 'standard'

        toolbars:
            standard: [ [ 'Source', '-', 'Save' ], '/', [ 'Anchor' ], '/', [ 'Maximize' ] ]
