framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    esi: true
    php_errors:
        log: true

    cache: ~
    fragments: ~
    translator: { fallbacks: [de] }
    form: ~
    csrf_protection:
        enabled: true
    validation:
        enable_annotations: true
        #cache: validator.mapping.cache.doctrine.apc
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    session:
        handler_id:  session.handler.native_file
        save_path:   '%kernel.root_dir%/../var/sessions/%kernel.environment%'
    http_method_override: true
    assets: ~
    router:
        strict_requirements: ~
