overblog_graphql:
    definitions:
        schema:
            quickstart:
                query: Query
                resolver_maps:
                    - App\GraphQL\Resolver\MyResolverMap

        mappings:
            auto_discover: false
            types:
                - type: graphql
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: ~
