jms_serializer:
  property_naming:
    lower_case: false
  visitors:
    json_serialization:
      options: 0 # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
    json_deserialization:
      options: 0 # json_decode options bitmask