liip_imagine:
    resolvers:
       default:
          web_path: ~
    driver: imagick

    loaders:
        photo_flystem_loader:
            flysystem:
                filesystem_service:  oneup_flysystem.flysystem_photo_photo_filesystem
        user_photo_flystem_loader:
            flysystem:
                filesystem_service:  oneup_flysystem.flysystem_user_photo_filesystem

        city_image_flystem_loader:
            flysystem:
                filesystem_service:  oneup_flysystem.flysystem_city_image_filesystem

    filter_sets:
        cache: ~

        gallery_photo_thumb:
            data_loader: photo_flystem_loader
            quality: 40
            filters:
                thumbnail: { size: [400, 300], mode: inset }
        gallery_photo_standard:
            data_loader: photo_flystem_loader
            quality: 60
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
                watermark:
                    image: ../public/images/watermark/criticalmass.png
                    size: 0.15
                    position: bottomright
        gallery_photo_blurred:
            data_loader: photo_flystem_loader
            quality: 30
            filters:
                thumbnail: { size: [800, 800], mode: inset }
                fast_blur_filter: ~
        gallery_photo_large:
            data_loader: photo_flystem_loader
            quality: 60
            filters:
                thumbnail: { size: [2000, 2000], mode: inset }
                watermark:
                    image: ../public/images/watermark/criticalmass.png
                    size: 0.15
                    position: bottomright

        user_profile_photo_medium:
            data_loader: user_photo_flystem_loader
            quality: 75
            filters:
                thumbnail: { size: [512, 512], mode: inset }
        user_profile_photo_small:
            data_loader: user_photo_flystem_loader
            quality: 50
            filters:
                thumbnail: { size: [128, 128], mode: inset }
        user_profile_photo_timelapse:
            data_loader: user_photo_flystem_loader
            quality: 30
            filters:
                thumbnail: { size: [50, 50], mode: inset }

        city_image_wide:
            data_loader: city_image_flystem_loader
            quality: 60
            filters:
                thumbnail: { size: [1140, 250], mode: inset }
        ride_image_wide:
            quality: 60
            filters:
                thumbnail: { size: [1140, 250], mode: inset }
        blog_featuredphoto_standard:
            quality: 80
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
        facebook_preview_image:
            quality: 60
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
        twitter_summary_large_image:
            quality: 50
            filters:
                thumbnail: { size: [800, 800], mode: inset }
        ride_photo_preview:
            quality: 50
            filters:
                thumbnail: { size: [600, 600], mode: inset }
        frontpage_teaser_large:
            quality: 75
            filters:
                thumbnail: { size: [2000, 2000], mode: inset }

        crawled_preview_image:
            cache: App\Criticalmass\Imagine\CacheResolver\RemoteCacheResolver
            data_loader: App\Criticalmass\Imagine\DataLoader\RemoteStreamLoader
            quality: 40
            filters:
                thumbnail: { size: [250, 250], mode: inset }
