old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        view:
            connection:       default
            exchange_options: { name: 'view', type: direct }
    consumers:
        view:
            connection:       default
            exchange_options: { name: 'view', type: direct }
            queue_options:    { name: 'view'}
            callback:         App\Consumer\ViewConsumer
    batch_consumers:
        view:
            connection:       default
            exchange_options: { name: 'view', type: fanout }
            queue_options:    { name: 'view' }
            callback:         App\Consumer\ViewBatchConsumer
            qos_options:      { prefetch_size: 0, prefetch_count: 50000, global: false }
            timeout_wait:     5
            auto_setup_fabric: false
            idle_timeout_exit_code: -2
            keep_alive: true
            graceful_max_execution:
                timeout: 600
