oneup_flysystem:
    adapters:
        photo_photo_adapter:
            local:
                directory: '%kernel.project_dir%/public/photos'
        user_photo_adapter:
            local:
                directory: '%kernel.project_dir%/public/users'
        city_image_adapter:
            local:
                directory: '%kernel.project_dir%/public/cities'
        ride_image_adapter:
            local:
                directory: '%kernel.project_dir%/public/rides'
        frontpage_teaser_adapter:
            local:
                directory: '%kernel.project_dir%/public/teaser'
        track_track_adapter:
            local:
                directory: '%kernel.project_dir%/public/tracks'

    filesystems:
        flysystem_photo_photo:
            adapter: photo_photo_adapter
            mount: flysystem_photo_photo

        flysystem_user_photo:
            adapter: user_photo_adapter
            mount: flysystem_user_photo

        flysystem_city_image:
            adapter: city_image_adapter
            mount: flysystem_city_image

        flysystem_ride_image:
            adapter: ride_image_adapter
            mount: flysystem_ride_image

        flysystem_frontpage_teaser:
            adapter: frontpage_teaser_adapter
            mount: flysystem_frontpage_teaser

        flysystem_track_track:
            adapter: frontpage_teaser_adapter
            mount: flysystem_track_track