oneup_flysystem:
    adapters:
        photo_photo_adapter:
            local:
                directory: '%kernel.project_dir%/public/photos'
        user_photo_adapter:
            local:
                directory: '%kernel.project_dir%/public/users'
        city_image_adapter:
            local:
                directory: '%kernel.project_dir%/public/cities'

    filesystems:
        flysystem_photo_photo:
            adapter: photo_photo_adapter
            mount: flysystem_photo_photo

        flysystem_user_photo:
            adapter: user_photo_adapter
            mount: flysystem_user_photo

        flysystem_city_image:
            adapter: city_image_adapter
            mount: flysystem_city_image