oneup_flysystem:
    adapters:
        photo_photo_adapter:
            local:
                directory: '%kernel.project_dir%/public/photos'

    filesystems:
        flysystem_photo_photo:
            adapter: photo_photo_adapter
            mount: flysystem_photo_photo