###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    rabbitmq:
      image: rabbitmq
      container_name: criticalmass-rabbitmq

    memcached:
      image: memcached:alpine
      container_name: criticalmass-memcached

    redis:
      image: redis:alpine
      container_name: criticalmass-redis

    mysql:
      image: mysql:5.6
      container_name: criticalmass-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=criticalmass
        - MYSQL_USER=criticalmass
        - MYSQL_PASSWORD=criticalmass
      ports:
        - "8002:3306"

    elasticsearch:
      image: elasticsearch:7.4.2
      container_name: criticalmass-elasticsearch
