caldera_criticalmass_api_app_list:
    pattern: /app/list
    defaults: { _controller: CalderaCriticalmassApiBundle:App:list }

caldera_criticalmass_api_app_add:
    pattern: /app/add
    defaults: { _controller: CalderaCriticalmassApiBundle:App:add }

caldera_criticalmass_api_app_edit:
    pattern: /app/edit/{appId}
    defaults: { _controller: CalderaCriticalmassApiBundle:App:edit }

caldera_criticalmass_api_app_delete:
    pattern: /app/delete/{appId}
    defaults: { _controller: CalderaCriticalmassApiBundle:App:delete }

caldera_criticalmass_api_documentation:
    pattern: /app/api
    defaults: { _controller: CalderaCriticalmassApiBundle:App:api }

CalderaCriticalmassCoreBundle_Api:
    resource: "@CalderaCriticalmassApiBundle/Resources/config/routing/cities.yml"
    prefix:   /api/cities

CalderaCriticalmassApiBundle_Api_Ride:
    resource: "@CalderaCriticalmassApiBundle/Resources/config/routing/ride.yml"
    prefix:   /api/ride

CalderaCriticalmassApiBundle_Api_User:
    resource: "@CalderaCriticalmassApiBundle/Resources/config/routing/user.yml"
    prefix:   /api/user

CalderaCriticalmassApiBundle_Api_TileLayer:
    resource: "@CalderaCriticalmassApiBundle/Resources/config/routing/tilelayer.yml"
    prefix:   /api/tilelayer

caldera_criticalmass_mapdata:
    pattern: /api/completemapdata/{citySlug}
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:completemapdata }

caldera_criticalmass_gpsinterval:
    pattern: /api/gpsinterval
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:gpsinterval }

caldera_criticalmass_gpsstatus:
    pattern: /api/gpsstatus
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:gpsstatus }

caldera_criticalmass_trackposition:
    pattern: /api/trackposition/{citySlug}
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:trackposition }

caldera_criticalmass_getgpsstatus:
    pattern: /api/getgpsstatus
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:getgpsstatus }

caldera_criticalmass_getgpsinterval:
    pattern: /api/getgpsinterval
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:getgpsinterval }