CalderaCriticalmassCoreBundle_Api:
    resource: "@CalderaCriticalmassApiBundle/Resources/config/routing/cities.yml"
    prefix:   /api/cities

caldera_criticalmass_mapdata:
    pattern: /api/completemapdata/{citySlug}
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:completemapdata }

caldera_criticalmass_gpsinterval:
    pattern: /api/gpsinterval
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:gpsinterval }

caldera_criticalmass_gpsstatus:
    pattern: /api/gpsstatus
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:gpsstatus }

caldera_criticalmass_trackposition:
    pattern: /api/trackposition
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:trackposition }

caldera_criticalmass_getgpsstatus:
    pattern: /api/getgpsstatus
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:getgpsstatus }

caldera_criticalmass_getgpsinterval:
    pattern: /api/getgpsinterval
    defaults: { _controller: CalderaCriticalmassApiBundle:Api:getgpsinterval }