parameters:
#    caldera_criticalmass_api.example.class: Caldera\CriticalmassApiBundle\Example

services:
#    caldera_criticalmass_api.example:
#        class: %caldera_criticalmass_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
