parameters:
#    caldera_criticalmass_openweather.example.class: Caldera\CriticalmassOpenweatherBundle\Example

services:
#    caldera_criticalmass_openweather.example:
#        class: %caldera_criticalmass_openweather.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
