caldera_criticalmass_selectcity:
    pattern: /
    defaults: { _controller: CalderaCriticalmassBundle:Default:selectcity }

caldera_criticalmass_choosecity:
    pattern: /selectcity/{latitude}/{longitude}
    defaults: { _controller: CalderaCriticalmassBundle:Default:choosecity }

caldera_criticalmass_registeruser:
    pattern: /register
    defaults: { _controller: CalderaCriticalmassBundle:Account:register }

caldera_criticalmass_processuserregistration:
    pattern: /processregistration
    defaults: { _controller: CalderaCriticalmassBundle:Account:processregistration }

caldera_criticalmass_showcity:
    pattern: /show/{city}
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }

caldera_criticalmass_trackposition:
    pattern: /trackposition
    defaults: { _controller: CalderaCriticalmassBundle:Default:trackposition }

caldera_criticalmass_mapcenter:
    pattern: /mapapi/mapcenter
    defaults: { _controller: CalderaCriticalmassBundle:Map:mapdata }

