caldera_criticalmass_selectcity:
    pattern: /
    defaults: { _controller: CalderaCriticalmassBundle:Default:selectcity }

caldera_criticalmass_choosecity:
    pattern: /selectcity/{latitude}/{longitude}
    defaults: { _controller: CalderaCriticalmassBundle:Default:choosecity }

caldera_criticalmass_registeruser:
    pattern: /register
    defaults: { _controller: CalderaCriticalmassBundle:Account:register }

caldera_criticalmass_showcity:
    pattern: /show/{city}
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }

