caldera_criticalmass_selectcity:
    pattern: /
    defaults: { _controller: CalderaCriticalmassBundle:Default:selectcity }

caldera_criticalmass_choosecity:
    pattern: /selectcity/{latitude}/{longitude}
    defaults: { _controller: CalderaCriticalmassBundle:Default:choosecity }

caldera_criticalmass_showcity:
    pattern: /{citySlug}/show/
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }

caldera_criticalmass_staticpage:
    pattern: /static/{page}
    defaults: { _controller: CalderaCriticalmassBundle:StaticPage:show }

caldera_criticalmass_loadcities:
    pattern: /loadcities/
    defaults: { _controller: CalderaCriticalmassBundle:City:loadcities }

caldera_criticalmass_live:
    pattern: /{citySlug}/live
    defaults: { _controller: CalderaCriticalmassBundle:Live:show }

caldera_criticalmass_pushnotificationsettings:
    pattern: /profile/pushnotifications
    defaults: { _controller: CalderaCriticalmassBundle:Default:pushnotifications }

CalderaCriticalmassBundle_admin_ride:
    resource: "@CalderaCriticalmassBundle/Resources/config/routing/ride.yml"
    prefix:   /admin/ride

CalderaCriticalmassBundle_ridecomments:
    resource: "@CalderaCriticalmassBundle/Resources/config/routing/ridecomments.yml"
    prefix:   /

caldera_criticalmass_godmode:
    pattern: /{citySlug}/godmode/{status}
    defaults: { _controller: CalderaCriticalmassBundle:Live:godmode }

caldera_criticalmass_showcity2:
    pattern: /{citySlug}
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }
