caldera_criticalmass_selectcity:
    pattern: /
    defaults: { _controller: CalderaCriticalmassBundle:Default:selectcity }

caldera_criticalmass_choosecity:
    pattern: /selectcity/{latitude}/{longitude}
    defaults: { _controller: CalderaCriticalmassBundle:Default:choosecity }

caldera_criticalmass_showcity:
    pattern: /{city}
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }

caldera_criticalmass_registeruser:
    pattern: /registeruser
    defaults: { _controller: CalderaCriticalmassBundle:Default:registeruser }