caldera_criticalmass_selectcity:
    pattern: /
    defaults: { _controller: CalderaCriticalmassBundle:Default:selectcity }

caldera_criticalmass_showcity:
    pattern: /{city}
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }