caldera_criticalmass_selectcity:
    pattern: /
    defaults: { _controller: CalderaCriticalmassBundle:Default:selectcity }

caldera_criticalmass_choosecity:
    pattern: /selectcity/{latitude}/{longitude}
    defaults: { _controller: CalderaCriticalmassBundle:Default:choosecity }



caldera_criticalmass_processuserregistration:
    pattern: /processregistration
    defaults: { _controller: CalderaCriticalmassBundle:Account:processregistration }

caldera_criticalmass_showcity:
    pattern: /{citySlug}/show/
    defaults: { _controller: CalderaCriticalmassBundle:Default:showcity }

caldera_criticalmass_trackposition:
    pattern: /trackposition
    defaults: { _controller: CalderaCriticalmassBundle:Live:trackposition }

caldera_criticalmass_mapdata:
    pattern: /mapapi/mapdata
    defaults: { _controller: CalderaCriticalmassBundle:Map:mapdata }

caldera_criticalmass_staticpage:
    pattern: /static/{page}
    defaults: { _controller: CalderaCriticalmassBundle:StaticPage:show }

caldera_criticalmass_loadcities:
    pattern: /loadcities/
    defaults: { _controller: CalderaCriticalmassBundle:City:loadcities }

caldera_criticalmass_listcomments:
    pattern: /{citySlug}/comments/list
    defaults: { _controller: CalderaCriticalmassBundle:Comment:listcomments }

caldera_criticalmass_addcomment:
    pattern: /{citySlug}/comments/add
    defaults: { _controller: CalderaCriticalmassBundle:Comment:addcomment }

caldera_criticalmass_live:
    pattern: /{citySlug}/live
    defaults: { _controller: CalderaCriticalmassBundle:Live:show }

caldera_criticalmass_settings_gps_interval:
    pattern: /settings/gpsinterval
    defaults: { _controller: CalderaCriticalmassBundle:Live:refreshgpsinterval }

caldera_criticalmass_settings_gps_status:
    pattern: /settings/gpsstatus
    defaults: { _controller: CalderaCriticalmassBundle:Live:refreshgpsstatus }

caldera_criticalmass_settings_gps_getinterval:
    pattern: /settings/getgpsinterval
    defaults: { _controller: CalderaCriticalmassBundle:Live:getinterval }

caldera_criticalmass_settings_gps_getstatus:
    pattern: /settings/getgpsstatus
    defaults: { _controller: CalderaCriticalmassBundle:Live:getstatus }

caldera_criticalmass_getridelocation:
    pattern: /mapapi/getridelocation/{citySlug}
    defaults: { _controller: CalderaCriticalmassBundle:Map:ridelocation }

CalderaCriticalmassBundle_admin_ride:
    resource: "@CalderaCriticalmassBundle/Resources/config/routing/ride.yml"
    prefix:   /admin/ride