parameters:
#    caldera_criticalmass.example.class: Caldera\CriticalmassBundle\Example

services:
#    caldera_criticalmass.example:
#        class: %caldera_criticalmass.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    caldera_criticalmass_ride_repository:
        class:           Caldera\CriticalmassBundle\Entity\RideRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [CalderaCriticalmassBundle:Ride]

    caldera_criticalmass_citydistancecalculator:
        class:           Caldera\CriticalmassBundle\Utility\CityDistanceCalculator
        arguments: []

    caldera_criticalmass_citylistener:
        class: Caldera\CriticalmassBundle\Listener\CityListener
        arguments: [@doctrine]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
