parameters:
#    caldera_criticalmass.example.class: Caldera\CriticalmassBundle\Example

services:
#    caldera_criticalmass.example:
#        class: %caldera_criticalmass.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    caldera_criticalmass_imageresizer:
        class:     Caldera\CriticalmassBundle\Utility\ImageResizer
        arguments: [@service_container]

    caldera_criticalmass_imageuploader:
        class:     Caldera\CriticalmassBundle\Utility\CommentImageUploader
        arguments: [@security.context, @service_container]