parameters:
#    caldera_criticalmass.example.class: Caldera\CriticalmassBundle\Example

services:
#    caldera_criticalmass.example:
#        class: %caldera_criticalmass.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
