parameters:
#    caldera_criticalmass_rocks.example.class: Caldera\Bundle\CriticalmassRocksBundle\Example

services:
#    caldera_criticalmass_rocks.example:
#        class: %caldera_criticalmass_rocks.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
