services:
    sonata.admin.helpclass:
        class: Caldera\CriticalmassContentBundle\Admin\ContentClassAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Class" }
        arguments:
            - ~
            - Caldera\CriticalmassContentBundle\Entity\ContentClass
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassContentBundle]]

    sonata.admin.helpitem:
        class: Caldera\CriticalmassContentBundle\Admin\ContentItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Item" }
        arguments:
            - ~
            - Caldera\CriticalmassContentBundle\Entity\ContentItem
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassContentBundle]]