caldera_criticalmass_content_display:
    pattern:  /content/{slug}
    defaults: { _controller: CalderaCriticalmassContentBundle:Content:show }

caldera_criticalmass_content_edit:
    pattern:  /content/{slug}/edit
    defaults: { _controller: CalderaCriticalmassContentBundle:Content:edit }
