parameters:
#    caldera_criticalmass_content.example.class: Caldera\CriticalmassContentBundle\Example

services:
#    caldera_criticalmass_content.example:
#        class: %caldera_criticalmass_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
