assetic:
    assets:
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../src/Caldera/CriticalmassAssetBundle/Resources/public/fonts/glyphicons/social/glyphicons-social-regular.ttf
            output: "fonts/glyphicons-social-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../src/Caldera/CriticalmassAssetBundle/Resources/public/fonts/glyphicons/social/glyphicons-social-regular.eot
            output: "fonts/glyphicons-social-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                 - %kernel.root_dir%/../src/Caldera/CriticalmassAssetBundle/Resources/public/fonts/glyphicons/social/glyphicons-social-regular.svg
            output: "fonts/glyphicons-social-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../src/Caldera/CriticalmassAssetBundle/Resources/public/fonts/glyphicons/social/glyphicons-social-regular.woff
            output: "fonts/glyphicons-social-regular.woff"