parameters:
#    caldera_criticalmass_asset.example.class: Caldera\CriticalmassAssetBundle\Example

services:
#    caldera_criticalmass_asset.example:
#        class: %caldera_criticalmass_asset.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
