caldera_criticalmass_desktop_city_list:
    path:  /citylist
    defaults: { _controller: CalderaBundle:City:list }

caldera_criticalmass_desktop_city_show:
    path:  /{citySlug}
    defaults: { _controller: CalderaBundle:City:show }
    options:
        expose: true

caldera_criticalmass_desktop_city_listrides:
    path:  /{citySlug}/list
    defaults: { _controller: CalderaBundle:City:listRides }

caldera_criticalmass_desktop_city_missingstats:
    path:  /{citySlug}/missingstats
    defaults: { _controller: CalderaBundle:City:missingStats }

caldera_criticalmass_desktop_city_listgalleries:
    path:  /{citySlug}/galleries
    defaults: { _controller: CalderaBundle:City:listGalleries }

caldera_criticalmass_desktop_city_live:
    path:  /{citySlug}/live
    defaults: { _controller: CalderaBundle:City:live }

caldera_criticalmass_city_locations:
    path:  /{citySlug}/locations
    defaults: { _controller: CalderaBundle:City:getlocations }
