caldera_criticalmass_track_delete:
    path:  /track/delete/{trackId}
    defaults: { _controller: CalderaBundle:Track:delete }
    options:
        expose: true

caldera_criticalmass_track_toggle:
    path:  /track/toggle/{trackId}
    defaults: { _controller: CalderaBundle:Track:toggle }

caldera_criticalmass_track_download:
    path:  /track/download/{trackId}
    defaults: { _controller: CalderaBundle:Track:download }

caldera_criticalmass_track_gpxgenerate:
    path:  /track/generate/{rideId}
    defaults: { _controller: CalderaBundle:Track:gpxgenerate }

caldera_criticalmass_track_list:
    path:  /track/list
    defaults: { _controller: CalderaBundle:Track:list }

caldera_criticalmass_track_upload:
    path:  /{citySlug}/{rideDate}/addtrack
    defaults: { _controller: CalderaBundle:Track:upload }

caldera_criticalmass_track_view:
    path:  /track/view/{trackId}
    defaults: { _controller: CalderaBundle:Track:view }

caldera_criticalmass_track_range:
    path:  /track/range/{trackId}
    defaults: { _controller: CalderaBundle:Track:range }

caldera_criticalmass_track_time:
    path:  /track/time/{trackId}
    defaults: { _controller: CalderaBundle:Track:time }

caldera_criticalmass_track_draw:
    path:  /{citySlug}/{rideDate}/drawtrack
    defaults: { _controller: CalderaBundle:Track:draw }

caldera_criticalmass_track_edit:
    path:  /track/edit/{trackId}
    defaults: { _controller: CalderaBundle:Track:edit }
