services:
    caldera.criticalmass.timeline:
        class: Caldera\Bundle\CriticalmassCoreBundle\Timeline\Timeline
        arguments: [@doctrine, @templating]
        calls:
            - [addCollector, ['@caldera.criticalmass.timeline.collector.ridephoto']]
            - [addCollector, ['@caldera.criticalmass.timeline.collector.ridetrack']]
            - [addCollector, ['@caldera.criticalmass.timeline.collector.rideparticipationestimate']]

    caldera.criticalmass.timeline.collector.ridephoto:
        class: Caldera\Bundle\CriticalmassCoreBundle\Timeline\Collector\RidePhotoCollector
        arguments: [@doctrine]

    caldera.criticalmass.timeline.collector.ridetrack:
        class: Caldera\Bundle\CriticalmassCoreBundle\Timeline\Collector\RideTrackCollector
        arguments: [@doctrine]

    caldera.criticalmass.timeline.collector.rideparticipationestimate:
        class: Caldera\Bundle\CriticalmassCoreBundle\Timeline\Collector\RideParticipationEstimateCollector
        arguments: [@doctrine]