services:
    caldera_criticalmass.twig.extension:
        class: Caldera\Bundle\CriticalmassCoreBundle\Twig\Extension\SiteTwigExtension
        arguments:
            - '@translator'
            - '@caldera.parser.multistep'
            - '@caldera.html_metadata'
            - '@router'
        tags:
            - { name: twig.extension }

    caldera_criticalmass.twig.router_extension:
        class: Caldera\Bundle\CriticalmassCoreBundle\Twig\Extension\RouterTwigExtension
        arguments:
            - '@caldera.criticalmass.routing.object_router'
        tags:
            - { name: twig.extension }