caldera_criticalmass_api_cities_listall:
    pattern: /listall
    defaults: { _controller: CalderaCriticalmassApiBundle:Cities:listall }

caldera_criticalmass_api_cities_getbyslug:
    pattern: /getbyslug/{citySlug}
    defaults: { _controller: CalderaCriticalmassApiBundle:Cities:getbyslug }