caldera_criticalmass_api_user_userloginstatus:
    pattern: /userloginstatus
    defaults: { _controller: CalderaCriticalmassApiBundle:User:userloginstatus }

caldera_criticalmass_api_user_getcolors:
    pattern: /getcolors
    defaults: { _controller: CalderaCriticalmassApiBundle:User:getcolors }

caldera_criticalmass_api_user_setcolors:
    pattern: /setcolors
    defaults: { _controller: CalderaCriticalmassApiBundle:User:setcolors }