caldera_criticalmass_api_user_userloginstatus:
    pattern: /userloginstatus
    defaults: { _controller: CalderaCriticalmassApiBundle:User:userloginstatus }

caldera_criticalmass_api_user_getcolors:
    pattern: /getcolors
    defaults: { _controller: CalderaCriticalmassApiBundle:User:getcolors }

caldera_criticalmass_api_user_setcolors:
    pattern: /setcolors
    defaults: { _controller: CalderaCriticalmassApiBundle:User:setcolors }

caldera_criticalmass_api_user_getpingtoken:
    pattern: /getpingtoken
    defaults: { _controller: CalderaCriticalmassApiBundle:User:getpingtoken }

caldera_criticalmass_api_user_switchcity:
    pattern: /switchcity/{citySlug}
    defaults: { _controller: CalderaCriticalmassApiBundle:User:switchcity }