services:
    sonata.admin.voucherclass:
        class: Caldera\CriticalmassPlusBundle\Admin\VoucherClassAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Plus", label: "Voucher Class" }
        arguments:
            - ~
            - Caldera\CriticalmassPlusBundle\Entity\VoucherClass
            - ~
        calls:
            - [ setTranslationDomain, [CriticalmassPlusBundle]]