parameters:
#    caldera_criticalmass_plus.example.class: Caldera\CriticalmassPlusBundle\Example

services:
#    caldera_criticalmass_plus.example:
#        class: %caldera_criticalmass_plus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
