caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    defaults: { _controller: CalderaCriticalmassRestBundle:City:show }

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/current
    defaults: { _controller: CalderaCriticalmassRestBundle:Ride:showCurrent }

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/{rideDate}
    defaults: { _controller: CalderaCriticalmassRestBundle:Ride:show }
