imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

    - { resource: criticalmass/fos.yml }
    - { resource: criticalmass/sonata.yml }
    - { resource: criticalmass/audit.yml }
    - { resource: criticalmass/doctrine.yml }
    - { resource: criticalmass/framework.yml }
    - { resource: criticalmass/sonata.yml }
    - { resource: criticalmass/jms.yml }
    - { resource: criticalmass/swiftmailer.yml }
    - { resource: criticalmass/twig.yml }
    - { resource: criticalmass/vich.yml }
    - { resource: criticalmass/liip.yml }
    - { resource: criticalmass/knp.yml }
    - { resource: criticalmass/nelmio.yml }
    - { resource: criticalmass/hwi.yml }
    - { resource: services.yml }
