services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Criticalmass\Bundle\AppBundle\:
        resource: '../../src/Criticalmass/Bundle/AppBundle/*'
        exclude: '../../src/Criticalmass/Bundle/AppBundle/{Entity,Repository,Tests}'

    Criticalmass\Bundle\AppBundle\Controller\:
        resource: '../../src/Criticalmass/Bundle/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Criticalmass\Component\:
        resource: '../../src/Criticalmass/Component/*'

    Criticalmass\Component\Image\PhotoUploader\PhotoUploader:
        arguments:
            $uploadDestinationPhoto: %upload_destination.photo%
    Criticalmass\Component\Image\PhotoGps\PhotoGps:
        arguments:
            $uploadDestinationPhoto: %upload_destination.photo%

    Cmfcmf\OpenWeatherMap: ~

