services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    gelf.publisher:
        class: Gelf\MessagePublisher
        arguments: ['%graylog.hostname%', '%graylog.port%']

    monolog.gelf_handler:
        class: Monolog\Handler\GelfHandler
        arguments: ['@gelf.publisher', 'error']

    caldera.oauth_success_handler:
        class: AppBundle\Authentication\CriticalAuthenticationSuccessHandler
        arguments: ['@security.http_utils']