services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    gelf.transport:
        class: Gelf\Transport\UdpTransport
        arguments:
            - '%graylog.hostname%'
            - '%graylog.port%'

    gelf.publisher:
        class: Gelf\Publisher
        calls:
            - method: addTransport
              arguments:
                  - '@gelf.transport'

    monolog.gelf_handler:
        class: Monolog\Handler\GelfHandler
        arguments: ['@gelf.publisher', 'error']