
caldera_criticalmass_statistic_track_deleteconfirm:
    pattern:  /delete/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:delete }

caldera_criticalmass_statistic_track_toggle:
    pattern:  /toggle/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:toggle }

caldera_criticalmass_statistic_track_download:
    pattern:  /download/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:download }

caldera_criticalmass_statistic_gpxgenerate:
    pattern:  /generate/{rideId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:gpxgenerate }

caldera_criticalmass_statistic_track_list:
    pattern:  /list
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:list }

caldera_criticalmass_statistic_track_upload:
    pattern:  /upload
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:upload }

caldera_criticalmass_statistic_track_setride:
    pattern:  /setride/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:setRide }

caldera_criticalmass_statistic_track_upload_failed:
    pattern:  /upload/failed
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:uploadFailed }

caldera_criticalmass_statistic_track_view:
    pattern:  /view/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:view }
