caldera_criticalmass_ride_addestimate:
    path:  /{citySlug}/{rideDate}/addestimate
    defaults: { _controller: App:Ride/RideEstimate:addestimate }

caldera_criticalmass_ride_addestimate_anonymous:
    path:  /{citySlug}/{rideDate}/anonymousestimate
    defaults: { _controller: App:Ride/RideEstimate:anonymousestimate }
