criticalmass_socialnetwork_city_list:
    path:  /{citySlug}/socialnetwork/list
    defaults: { _controller: App:SocialNetwork/SocialNetworkList:listCity }

criticalmass_socialnetwork_ride_list:
    path:  /{citySlug}/{rideDate}/socialnetwork/list
    defaults: { _controller: App:SocialNetwork/SocialNetworkList:listRide }
    requirements:
        rideDate: '([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})'

criticalmass_socialnetwork_city_add:
    path:  /{citySlug}/socialnetwork/add
    defaults: { _controller: App:SocialNetwork/SocialNetwork:add }

criticalmass_socialnetwork_ride_add:
    path:  /{citySlug}/{rideDate}/socialnetwork/add
    defaults: { _controller: App:SocialNetwork/SocialNetwork:add }
    requirements:
        rideDate: '([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})'

criticalmass_socialnetwork_disable:
    path:  /socialnetwork/{profileId}/disable
    defaults: { _controller: App:SocialNetwork/SocialNetwork:disable }
