parameters:
#    caldera_criticalmass_twitter.example.class: Caldera\CriticalmassTwitterBundle\Example

services:
#    caldera_criticalmass_twitter.example:
#        class: %caldera_criticalmass_twitter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
