caldera_criticalmass_rest_ride_list:
    path:     /ride/list
    defaults: { _controller: CalderaBundle:Api/Ride:list }
    methods:  [GET]

caldera_criticalmass_rest_city_list:
    path:     /city/list
    defaults: { _controller: CalderaBundle:Api/City:list }
    methods:  [GET]

caldera_criticalmass_rest_photo_gallery:
    path:     /photo/gallery
    defaults: { _controller: CalderaBundle:Api/Photo:gallery }
    methods:  [GET]

caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    defaults: { _controller: CalderaBundle:Api/City:show }
    methods:  [GET]

caldera_criticalmass_rest_ride_show_current:
    path:     /{citySlug}/current
    defaults: { _controller: CalderaBundle:Api/Ride:showCurrent }
    methods:  [GET]

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/{rideDate}
    defaults: { _controller: CalderaBundle:Api/Ride:show }
    methods:  [GET]
