caldera_criticalmass_citycycle_list:
    path:  /{citySlug}/cycles/list
    defaults: { _controller: AppBundle:City/CityCycle:list }

caldera_criticalmass_citycycle_add:
    path:  /{citySlug}/cycles/add
    defaults: { _controller: AppBundle:City/CityCycle:add }