caldera_criticalmass_photo_ajaxview:
    path: /{citySlug}/{rideDate}/ajaxphotoview
    defaults: { _controller: AppBundle:Photo/Photo:ajaxphotoview }

caldera_criticalmass_photo_show_ride:
    path: /{citySlug}/{rideDate}/photo/{photoId}
    defaults: { _controller: AppBundle:Photo/Photo:show }
    requirements:
        rideDate: '^([0-9]{4,4})\-([0-9]{1,2})\-([0-9]{1,2})$'

caldera_criticalmass_photo_show_event:
    path: /{citySlug}/{eventSlug}/photo/{photoId}
    defaults: { _controller: AppBundle:Photo/Photo:show }
    requirements:
        eventSlug: '^([a-zA-Z0-9\-]*)$'
