caldera_criticalmass_photo_user_list:
    path: /photos/list
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:list }

caldera_criticalmass_photo_manage:
    path: /{citySlug}/{rideDate}/managephotos
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:manage }

caldera_criticalmass_photo_place_single:
    path: /{citySlug}/{rideDate}/managephotos/{photoId}/place
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:placeSingle }

caldera_criticalmass_photo_rotate:
    path: /{citySlug}/{rideDate}/managephotos/{photoId}/rotate
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:rotate }

caldera_criticalmass_photo_toggle:
    path: /{citySlug}/{rideDate}/photo/{photoId}/toggle
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:toggle }

caldera_criticalmass_photo_featured:
    path: /{citySlug}/{rideDate}/photo/{photoId}/featured
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:featuredPhoto }

caldera_criticalmass_photo_delete:
    path: /{citySlug}/{rideDate}/managephotos/{photoId}/delete
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:delete }

caldera_criticalmass_photo_relocate:
    path: /{citySlug}/{rideDate}/relocatephotos
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:relocate }

caldera_criticalmass_gallery_photos_rearrange:
    path: /{citySlug}/{rideDate}/gallery/rearrange
    defaults: { _controller: CalderaBundle:Photo/PhotoManagement:rearrange }
