caldera_criticalmass_search_query:
    path:  /search/query
    defaults: { _controller: AppBundle:Search:query }

caldera_criticalmass_search_prefetch:
    path:  /search/prefetch
    defaults: { _controller: AppBundle:Search:prefetch }
