caldera_criticalmass_statistic_city:
    path: /{citySlug}/statistic
    defaults: { _controller: CalderaBundle:Statistic:citystatistic }

caldera_criticalmass_statistic_ride:
    path: /{citySlug}/{rideDate}/statistic
    defaults: { _controller: CalderaBundle:Statistic:ridestatistic }

caldera_criticalmass_statistic_facebook:
    path: /facebookstatistic
    defaults: { _controller: CalderaBundle:Statistic:facebookstatistic }

caldera_criticalmass_statistic_overview:
    path: /statistic
    defaults: { _controller: CalderaBundle:Statistic:overview }
