caldera_criticalmass_strava_auth:
    path:  /{citySlug}/{rideDate}/stravaauth
    defaults: { _controller: AppBundle:Track/Strava:auth }

caldera_criticalmass_strava_token:
    path:  /{citySlug}/{rideDate}/stravatoken
    defaults: { _controller: AppBundle:Track/Strava:token }

caldera_criticalmass_strava_list:
    path:  /{citySlug}/{rideDate}/stravalist
    defaults: { _controller: AppBundle:Track/Strava:listrides }

caldera_criticalmass_strava_import:
    path:  /{citySlug}/{rideDate}/stravaimport
    defaults: { _controller: AppBundle:Track/Strava:import }
