parameters:
#    caldera_criticalmass_glympse.example.class: Caldera\CriticalmassGlympseBundle\Example

services:
#    caldera_criticalmass_glympse.example:
#        class: %caldera_criticalmass_glympse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
