caldera_criticalmass_blog_homepage:
    path:     /
    defaults: { _controller: CalderaCriticalmassBlogBundle:Default:index }

caldera_criticalmass_blog_post:
    path:     /{slug}
    defaults: { _controller: CalderaCriticalmassBlogBundle:Default:index }
