simple_things_entity_audit:
    audited_entities:
        - Criticalmass\Bundle\AppBundle\Entity\City
        - Criticalmass\Bundle\AppBundle\Entity\CityCycle
        - Criticalmass\Bundle\AppBundle\Entity\HelpCategory
        - Criticalmass\Bundle\AppBundle\Entity\HelpItem
        - Criticalmass\Bundle\AppBundle\Entity\Location
        - Criticalmass\Bundle\AppBundle\Entity\Region
        - Criticalmass\Bundle\AppBundle\Entity\Ride
        - Criticalmass\Bundle\AppBundle\Entity\Subride
        - Criticalmass\Bundle\AppBundle\Entity\SocialNetworkProfile

    global_ignore_columns:
        - created_at
        - updated_at
