caldera_criticalmass_live:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/live.yml"
    prefix: /

caldera_criticalmass_calendar:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/calendar.yml"
    prefix: /

caldera_criticalmass_post:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/post.yml"
    prefix: /post
    
caldera_criticalmass_track:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/track.yml"
    prefix: /

caldera_criticalmass_trackimport:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/trackimport.yml"
    prefix: /

caldera_criticalmass_blog:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/blog.yml"
    prefix: /

caldera_criticalmass_frontpage:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/frontpage.yml"
    prefix: /

caldera_criticalmass_content:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/content.yml"
    prefix: /content

caldera_criticalmass_search:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/search.yml"
    prefix: /

caldera_criticalmass_photo:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/photo.yml"
    prefix:   /

caldera_criticalmass_api:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/api.yml"
    prefix: /

caldera_criticalmass_city:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/city.yml"
    prefix: /

caldera_criticalmass_timelapse:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/timelapse.yml"
    prefix:   /
    
caldera_criticalmass_ride:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/ride.yml"
    prefix: /

caldera_criticalmass_timeline:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/timeline.yml"
    prefix: /

caldera_criticalmass_sudride:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/subride.yml"
    prefix: /

caldera_criticalmass_statistic:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing/statistic.yml"
    prefix:   /