caldera_criticalmass_ride_add:
    path:  /{citySlug}/add-ride
    defaults: { _controller: AppBundle:Ride/RideManagement:add }

caldera_criticalmass_ride_edit:
    path:  /{citySlug}/{rideDate}/edit
    defaults: { _controller: AppBundle:Ride/RideManagement:edit }

caldera_criticalmass_ride_facebookupdate:
    path:  /{citySlug}/{rideDate}/facebookupdate
    defaults: { _controller: AppBundle:Ride/RideManagement:facebookUpdate }

caldera_criticalmass_ride_socialpreview:
    path:  /{citySlug}/{rideDate}/socialpreview
    defaults: { _controller: AppBundle:Ride/RideManagement:socialPreview }
