caldera_criticalmass_statistic_city:
    path: /{citySlug}/statistic
    defaults: { _controller: AppBundle:Statistic:citystatistic }

caldera_criticalmass_statistic_ride:
    path: /{citySlug}/{rideDate}/statistic
    defaults: { _controller: AppBundle:Statistic:ridestatistic }

caldera_criticalmass_statistic_facebook:
    path: /facebookstatistic
    defaults: { _controller: AppBundle:Statistic/FacebookCityStatistic:facebookstatistic }

caldera_criticalmass_statistic_overview:
    path: /statistic
    defaults: { _controller: AppBundle:Statistic:overview }

caldera_criticalmass_statistic_participation_list:
    path: /statistic/{year}/{month}
    defaults: { _controller: AppBundle:Statistic:listRides }
