caldera_criticalmass_statistic_city:
    path: /{citySlug}/statistic
    defaults: { _controller: AppBundle:Statistic:citystatistic }

caldera_criticalmass_statistic_overview:
    path: /statistic
    defaults: { _controller: AppBundle:Statistic:overview }

caldera_criticalmass_statistic_ride_month:
    path: /statistic/{year}/{month}
    defaults: { _controller: AppBundle:Statistic:listRides }
