services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        tags:
            - { name: timeline.collector }

    Criticalmass\Component\Timeline\Collector\:
        resource: '%kernel.project_dir%/src/Criticalmass/Component/Timeline/Collector/*'
