services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true
        bind:
            $ttl: '%timeline.ttl%'

    Criticalmass\Component\Timeline\Timeline: ~
    Criticalmass\Component\Timeline\CachedTimeline: ~
