services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true
        # this works for Symfony 3.4
        # bind:
        #    $ttl: '%timeline.ttl%'

    Criticalmass\Component\Timeline\Timeline: ~
    Criticalmass\Component\Timeline\CachedTimeline:
        arguments: ['@doctrine', '@templating', '%timeline.ttl%']
