parameters:
#    caldera.example.class: Criticalmass\Bundle\AppBundle\Example

services:
    caldera.user_provider:
        class: Criticalmass\Bundle\AppBundle\UserProvider\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', {facebook: facebookId, strava: stravaId, runkeeper: runkeeperId}]

    caldera.criticalmass.gps.gpxexporter:
        class: Criticalmass\Component\Gps\GpxExporter\GpxExporter
        arguments: [ '@doctrine.orm.entity_manager', '@doctrine' ]

    caldera.criticalmass.gps.gpxreader:
        class: Criticalmass\Component\Gps\GpxReader\GpxReader
        arguments: [ '@vich_uploader.templating.helper.uploader_helper', '%kernel.root_dir%' ]

    caldera.criticalmass.gps.trackreader:
        class: Criticalmass\Component\Gps\GpxReader\TrackReader
        arguments: [ '@vich_uploader.templating.helper.uploader_helper', '%kernel.root_dir%' ]

    caldera.criticalmass.gps.latlnglistgenerator.simple:
        class: Criticalmass\Component\Gps\LatLngListGenerator\SimpleLatLngListGenerator
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.latlnglistgenerator.range:
        class: Criticalmass\Component\Gps\LatLngListGenerator\RangeLatLngListGenerator
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.latlnglistgenerator.time:
        class: Criticalmass\Component\Gps\LatLngListGenerator\TimeLatLngListGenerator
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.polyline.track:
        class: Criticalmass\Component\Gps\TrackPolyline\TrackPolyline
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.distancecalculator.track:
        class: Criticalmass\Component\Gps\DistanceCalculator\TrackDistanceCalculator
        arguments: [ '@doctrine', '@caldera.criticalmass.gps.trackreader' ]

    caldera.criticalmass.gps.timeshift.track:
        class: Criticalmass\Component\Gps\TrackTimeShift\TrackTimeShift
        arguments: [ '@doctrine', '@caldera.criticalmass.gps.trackreader', '@caldera.criticalmass.gps.gpxexporter' ]

    fos_user.doctrine_registry:
        alias: doctrine
