parameters:
#    caldera.example.class: Criticalmass\Bundle\AppBundle\Example

services:
    critical_markdown:
        class: Criticalmass\Component\Markdown\CriticalMarkdown

    caldera.user_provider:
        class: Criticalmass\Bundle\AppBundle\UserProvider\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', {facebook: facebookId, strava: stravaId, runkeeper: runkeeperId}]

    caldera.manager.post_manager:
        class: Criticalmass\Bundle\AppBundle\Manager\PostManager\PostManager
        arguments: ['@doctrine']

    caldera.criticalmass.routing.object_router:
        class: Criticalmass\Component\Router\ObjectRouter
        arguments:
            - '@router.default'

    caldera.criticalmass.gps.gpxexporter:
        class: Criticalmass\Component\Gps\GpxExporter\GpxExporter
        arguments: [ '@doctrine.orm.entity_manager', '@doctrine' ]

    caldera.criticalmass.gps.gpxreader:
        class: Criticalmass\Component\Gps\GpxReader\GpxReader
        arguments: [ '@vich_uploader.templating.helper.uploader_helper', '%kernel.root_dir%' ]

    caldera.criticalmass.gps.trackreader:
        class: Criticalmass\Component\Gps\GpxReader\TrackReader
        arguments: [ '@vich_uploader.templating.helper.uploader_helper', '%kernel.root_dir%' ]

    caldera.criticalmass.gps.latlnglistgenerator.simple:
        class: Criticalmass\Component\Gps\LatLngListGenerator\SimpleLatLngListGenerator
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.latlnglistgenerator.range:
        class: Criticalmass\Component\Gps\LatLngListGenerator\RangeLatLngListGenerator
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.latlnglistgenerator.time:
        class: Criticalmass\Component\Gps\LatLngListGenerator\TimeLatLngListGenerator
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.polyline.track:
        class: Criticalmass\Component\Gps\TrackPolyline\TrackPolyline
        arguments: [ '@caldera.criticalmass.gps.trackreader', '%track.gap_width%' ]

    caldera.criticalmass.gps.distancecalculator.track:
        class: Criticalmass\Component\Gps\DistanceCalculator\TrackDistanceCalculator
        arguments: [ '@doctrine', '@caldera.criticalmass.gps.trackreader' ]

    caldera.criticalmass.gps.timeshift.track:
        class: Criticalmass\Component\Gps\TrackTimeShift\TrackTimeShift
        arguments: [ '@doctrine', '@caldera.criticalmass.gps.trackreader', '@caldera.criticalmass.gps.gpxexporter' ]

    fos_user.doctrine_registry:
        alias: doctrine

    caldera.criticalmass.validator.single_ride_day:
        class: Criticalmass\Bundle\AppBundle\Validator\SingleRideForDayValidator
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: validator.constraint_validator }

    caldera.criticalmass.image.filter.blur:
        class: Criticalmass\Component\Image\Filter\BlurFilter
        tags:
            - { name: "liip_imagine.filter.loader", loader: blur_filter }

    caldera.criticalmass.image.filter.fast_blur:
        class: Criticalmass\Component\Image\Filter\FastBlurFilter
        tags:
            - { name: 'liip_imagine.filter.loader', loader: fast_blur_filter }
