parameters:
#    caldera_criticalmass_model.example.class: Caldera\Bundle\CriticalmassModelBundle\Example

services:
#    caldera_criticalmass_model.example:
#        class: %caldera_criticalmass_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
