caldera_criticalmass_listcomments:
    pattern: /{citySlug}/comments/list
    defaults: { _controller: CalderaCriticalmassBundle:Comment:listcomments }

caldera_criticalmass_addcomment:
    pattern: /{citySlug}/comments/add
    defaults: { _controller: CalderaCriticalmassBundle:Comment:addcomment }