caldera_criticalmass_multipage_index:
    pattern: /
    defaults: { _controller: CalderaCriticalmassMobileBundle:MultiPage:main }

caldera_criticalmass_multipage_slugindex:
    pattern: /{slug}
    defaults: { _controller: CalderaCriticalmassMobileBundle:MultiPage:slugindex }