parameters:
#    caldera_criticalmass_mobile.example.class: Caldera\CriticalmassMobileBundle\Example

services:
    caldera_criticalmasscore_citylistener:
        class: Caldera\CriticalmassCoreBundle\Listener\CityListener
        arguments: [@doctrine]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    caldera_criticalmassstatistic_statisticlistener:
        class: Caldera\CriticalmassStatisticBundle\Listener\StatisticListener
        arguments: [@doctrine]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }