parameters:
#    caldera_criticalmass_mobile.example.class: Caldera\CriticalmassMobileBundle\Example

services:
#    caldera_criticalmass_mobile.example:
#        class: %caldera_criticalmass_mobile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
