caldera_criticalmass_desktop_index:
    pattern:  /
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:index }

caldera_criticalmass_desktop_slugindex:
    pattern:  /{slug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:slugindex }

caldera_criticalmass_desktop_content_impress:
    pattern:  /content/about-us/impress
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:impress }

caldera_criticalmass_desktop_content_aboutus:
    pattern:  /content/about-us
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:aboutus }

caldera_criticalmass_desktop_content_criticalmass:
    pattern:  /content/criticalmass
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:criticalmass }

caldera_criticalmass_desktop_content_glympse:
    pattern:  /content/glympse
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:glympse }

caldera_criticalmass_desktop_city_list:
    pattern:  /city/list
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:list }

caldera_criticalmass_desktop_ride_list:
    pattern:  /ride/list
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:list }

caldera_criticalmass_desktop_ride_add:
    pattern:  /{citySlug}/addride
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:add }

caldera_criticalmass_desktop_city_add:
    pattern:  /city/add
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:add }

caldera_criticalmass_desktop_city_show:
    pattern:  /{citySlug}/show
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:show }

caldera_criticalmass_desktop_city_edit:
    pattern:  /{citySlug}/edit
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:edit }

caldera_criticalmass_desktop_ride_showcurrent:
    pattern:  /ride/showcurrent/{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:showcurrent }

caldera_criticalmass_desktop_ride_propose:
    pattern:  /ride/propose/{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:propose }

caldera_criticalmass_desktop_ride_edit:
    pattern:  /{citySlug}/{rideDate}/edit
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:edit }

caldera_criticalmass_desktop_statistic_participants:
    pattern: /statistic/participants
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Statistic:participants }

caldera_criticalmass_desktop_ride_show:
    pattern:  /{citySlug}/{rideDate}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:show }

caldera_criticalmass_desktop_content_show:
    pattern: /static/{classSlug}/{itemSlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Content:show }

caldera_criticalmass_desktop_ride_estimate:
    pattern: /ride/estimate/{rideId}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:estimateride }

caldera_criticalmass_desktop_subride:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/subride.yml"
    prefix: /subride