caldera_criticalmass_desktop_index:
    pattern:  /
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:index }

caldera_criticalmass_desktop_slugindex:
    pattern:  /{slug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:slugindex }

caldera_criticalmass_desktop_content_impress:
    pattern:  /content/about-us/impress
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:impress }

caldera_criticalmass_desktop_content_aboutus:
    pattern:  /content/about-us
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:aboutus }

caldera_criticalmass_desktop_content_criticalmass:
    pattern:  /content/criticalmass
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:criticalmass }

caldera_criticalmass_desktop_content_glympse:
    pattern:  /content/glympse
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:glympse }

caldera_criticalmass_desktop_statistic_participants:
    pattern: /statistic/participants
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Statistic:participants }

caldera_criticalmass_desktop_content_show:
    pattern: /static/{classSlug}/{itemSlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Content:show }

caldera_criticalmass_desktop_subride:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/subride.yml"
    prefix: /subride

caldera_criticalmass_desktop_city:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/city.yml"
    prefix: /

caldera_criticalmass_desktop_ride:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/ride.yml"
    prefix: /