caldera_criticalmass_desktop_index:
    pattern:  /
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:index }

caldera_criticalmass_desktop_slugindex:
    pattern:  /{slug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:slugindex }

caldera_criticalmass_desktop_city_list:
    pattern:  /city/list
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:list }

caldera_criticalmass_desktop_ride_showcurrent:
    pattern:  /ride/showcurrent/{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:showcurrent }

caldera_criticalmass_desktop_ride_propose:
    pattern:  /ride/propose/{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:propose }

caldera_criticalmass_desktop_statistic_participants:
    pattern: /statistic/participants
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Statistic:participants }

caldera_criticalmass_desktop_ride_show:
    pattern:  /{citySlug}/{rideId}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:show }

caldera_criticalmass_desktop_city_show:
    pattern: /{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:show }

caldera_criticalmass_desktop_content_show:
    pattern: /static/{classSlug}/{itemSlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Content:show }