caldera_criticalmass_desktop_homepage:
    pattern:  /hamburg
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Live:show }

caldera_criticalmass_desktop_city_list:
    pattern:  /city/list
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:list }

caldera_criticalmass_desktop_ride_showcurrent:
    pattern:  /ride/showcurrent/{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:showcurrent }

caldera_criticalmass_desktop_statistic_participants:
    pattern: /statistic/participants
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Statistic:participants }

caldera_criticalmass_desktop_ride_show:
    pattern:  /{citySlug}/{rideId}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:show }

caldera_criticalmass_desktop_city_show:
    pattern: /{citySlug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:City:show }
