caldera_criticalmass_desktop_homepage:
    pattern:  /hamburg
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Live:show }

caldera_criticalmass_desktop_showride:
    pattern:  /hamburg/{rideId}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Track:showride }
