caldera_criticalmass_desktop_homepage:
    pattern:  /desktop/hamburg/live
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Live:show }

caldera_criticalmass_desktop_showride:
    pattern:  /desktop/hamburg/{rideId}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Track:showride }
