caldera_criticalmass_desktop_index:
    pattern:  /
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:index }

caldera_criticalmass_desktop_statistic_participants:
    pattern: /statistic/participants
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Statistic:participants }

caldera_criticalmass_desktop_ride_estimate:
    pattern: /ride/estimate/{rideId}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Ride:estimateride }

caldera_criticalmass_desktop_subride:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/subride.yml"
    prefix: /subride

caldera_criticalmass_desktop_city:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/city.yml"
    prefix: /

caldera_criticalmass_desktop_ride:
    resource: "@CalderaCriticalmassDesktopBundle/Resources/config/routing/ride.yml"
    prefix: /

caldera_criticalmass_desktop_slugindex:
    pattern:  /{slug}
    defaults: { _controller: CalderaCriticalmassDesktopBundle:Default:slugindex }
