parameters:
#    caldera_criticalmass_desktop.example.class: Caldera\CriticalmassDesktopBundle\Example

services:
#    caldera_criticalmass_desktop.example:
#        class: %caldera_criticalmass_desktop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
