caldera_criticalmass_board_overview:
    pattern:  /boards/overview
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:overview }

caldera_criticalmass_board_listthreads:
    pattern:  /boards/{slug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:listthreads }

caldera_criticalmass_board_addthread:
    pattern:  /boards/{slug}/addthread
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:addcitythread }

caldera_criticalmass_board_citythread:
    pattern:  /{citySlug}/thread/{threadId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewcitythread }

caldera_criticalmass_board_addthread:
    pattern:  /boards/{slug}/addthread
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:addcitythread }

caldera_criticalmass_board_rideboard:
    pattern:  /{citySlug}/rideboard
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewrideboard }

caldera_criticalmass_board_ridethread:
    pattern:  /{citySlug}/{rideDate}/thread
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewridethread }