caldera_criticalmass_board_overview:
    pattern:  /boards/overview
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:overview }

caldera_criticalmass_board_talkboard:
    pattern:  /{citySlug}/threads
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewtalkboard }

caldera_criticalmass_board_citythread:
    pattern:  /{citySlug}/thread/{threadId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewcitythread }

caldera_criticalmass_board_rideboard:
    pattern:  /{citySlug}/rideboard
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewrideboard }

caldera_criticalmass_board_ridethread:
    pattern:  /{citySlug}/{rideDate}/thread
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewridethread }

caldera_criticalmass_board_imagecommentboard:
    pattern:  /{citySlug}/imagecommentboard
    defaults: { _controller: CalderaCriticalmassSiteBundle:Board:viewimagecommentboard }