caldera_criticalmass_chat_index:
    pattern:  /chat
    defaults: { _controller: CalderaCriticalmassSiteBundle:Chat:index }

caldera_criticalmass_chat_anonymoususername:
    pattern: /chat/anonymoususername
    defaults: { _controller: CalderaCriticalmassSiteBundle:Chat:createAnonymousName }