caldera_criticalmass_chat_index:
    path:  /chat
    defaults: { _controller: CalderaCriticalmassSiteBundle:Chat:index }

caldera_criticalmass_chat_anonymoususername:
    path: /chat/anonymoususername
    defaults: { _controller: CalderaCriticalmassSiteBundle:Chat:createAnonymousName }