caldera_criticalmass_desktop_city_show_seo:
    pattern:  /critical-mass-in-{citySlug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:show }

caldera_criticalmass_desktop_city_show_seo2:
    pattern:  /critical-mass-{citySlug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:show }

caldera_criticalmass_desktop_city_show:
    pattern:  /{citySlug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:show }

caldera_criticalmass_desktop_city_list:
    pattern:  /city/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:list }

caldera_criticalmass_desktop_city_listrides:
    pattern:  /{citySlug}/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:listRides }

caldera_criticalmass_desktop_city_live:
    pattern:  /{citySlug}/live
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:live }

caldera_criticalmass_desktop_city_edit:
    pattern:  /{citySlug}/edit
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:edit }

caldera_criticalmass_city_locations:
    pattern:  /{citySlug}/locations
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:getlocations }