caldera_criticalmass_desktop_city_list:
    pattern:  /city/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:list }

caldera_criticalmass_desktop_city_add:
    pattern:  /city/add
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:add }

caldera_criticalmass_desktop_city_show:
    pattern:  /{citySlug}/show
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:show }

caldera_criticalmass_desktop_city_live:
    pattern:  /{citySlug}/live
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:live }

caldera_criticalmass_desktop_city_show_short:
    pattern:  /{citySlug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:show }

caldera_criticalmass_desktop_city_edit:
    pattern:  /{citySlug}/edit
    defaults: { _controller: CalderaCriticalmassSiteBundle:City:edit }