caldera_criticalmass_content_edit:
    path:  /edit/{slug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Content:edit }
    requirements:
        slug: .+
        
caldera_criticalmass_content_display:
    path:  /{slug}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Content:show }
    requirements:
        slug: .+
