caldera_criticalmass_incidents_city:
    path:  /{citySlug}/incidents
    defaults: { _controller: CalderaCriticalmassSiteBundle:Incident:list }

caldera_criticalmass_incidents_ride:
    path:  /{citySlug}/{rideDate}/incidents
    defaults: { _controller: CalderaCriticalmassSiteBundle:Incident:list }

caldera_criticalmass_incident_add:
    path:  /{citySlug}/incidents/add
    defaults: { _controller: CalderaCriticalmassSiteBundle:Incident:add }