caldera_criticalmass_live:
    pattern:  /live
    defaults: { _controller: CalderaCriticalmassSiteBundle:Live:index }

caldera_criticalmass_live_city:
    pattern:  /{citySlug}/live
    defaults: { _controller: CalderaCriticalmassSiteBundle:Live:city }