caldera_criticalmass_photo_user_list:
    path: /photos/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:list }

caldera_criticalmass_photo_manage:
    path: /{citySlug}/{rideDate}/managephotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:manage }

caldera_criticalmass_photo_place_single:
    path: /{citySlug}/{rideDate}/managephotos/{photoId}/place
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:placeSingle }

caldera_criticalmass_photo_toggle:
    path: /{citySlug}/{rideDate}/photo/{photoId}/toggle
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:toggle }

caldera_criticalmass_photo_delete:
    path: /{citySlug}/{rideDate}/managephotos/{photoId}/delete
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:delete }

caldera_criticalmass_photo_relocate:
    path: /{citySlug}/{rideDate}/relocatephotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:relocate }

caldera_criticalmass_gallery_photos_rearrange:
    path: /{citySlug}/{rideDate}/gallery/rearrange
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoManagement:rearrange }