caldera_criticalmass_photo_user_list:
    pattern: /photos/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:userlist }

caldera_criticalmass_photo_manage:
    pattern: /{citySlug}/{rideDate}/managephotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:manage }

caldera_criticalmass_photo_relocate:
    pattern: /{citySlug}/{rideDate}/relocatephotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:relocate }

caldera_criticalmass_photo_toggle:
    pattern: /{citySlug}/{rideDate}/photo/{photoId}/toggle
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:toggle }

caldera_criticalmass_photo_delete:
    pattern: /{citySlug}/{rideDate}/managephotos/{photoId}/delete
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:delete }

caldera_criticalmass_photo_place_single:
    pattern: /{citySlug}/{rideDate}/managephotos/{photoId}/place
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:placeSingle }

caldera_criticalmass_gallery_photos_upload_ride_process:
    pattern: /{citySlug}/{rideDate}/processphoto
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:process }

caldera_criticalmass_gallery_photos_rearrange:
    pattern: /{citySlug}/{rideDate}/gallery/rearrange
    defaults: { _controller: CalderaCriticalmassSiteBundle:Gallery:rearrange }

caldera_criticalmass_gallery_photos_loadtrack:
    pattern: /gallery/loadtrack/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Gallery:loadtrack }

caldera_criticalmass_gallery_photos_loadphotos:
    pattern: /gallery/loadphotos/{rideId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Gallery:loadPhotos }

caldera_criticalmass_photo_ajaxview:
    pattern: /{citySlug}/{rideDate}/ajaxphotoview
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:ajaxphotoview }

caldera_criticalmass_photo_ride_list:
    pattern: /{citySlug}/{rideDate}/listphotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:ridelist }

caldera_criticalmass_photo_show:
    pattern: /{citySlug}/{rideDate}/photo/{photoId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:show }

caldera_criticalmass_photo_gallery:
    pattern: /cities/gallery
    defaults: { _controller: CalderaCriticalmassSiteBundle:Photo:citygallery }