caldera_criticalmass_photo_user_list:
    pattern: /photos/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoGallery:userlist }

caldera_criticalmass_photo_ride_list:
    pattern: /{citySlug}/{rideDate}/listphotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoGallery:ridelist }
    requirements:
        rideDate: "([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})"

caldera_criticalmass_photo_event_list:
    pattern:  /{citySlug}/{eventSlug}/listphotos
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoGallery:eventlist }
    requirements:
        rideDate: "^(*.)$"

caldera_criticalmass_photo_gallery:
    pattern: /cities/gallery
    defaults: { _controller: CalderaCriticalmassSiteBundle:PhotoGallery:citygallery }