caldera_criticalmass_region_world:
    path:     /world
    defaults: { _controller: CalderaCriticalmassSiteBundle:Region:index }

caldera_criticalmass_region_world_region_1:
    path:     /world/{slug1}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Region:index }

caldera_criticalmass_region_world_region_2:
    path:     /world/{slug1}/{slug2}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Region:index }

caldera_criticalmass_region_world_region_3:
    path:     /world/{slug1}/{slug2}/{slug3}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Region:index }
