caldera_criticalmass_desktop_ride_add:
    pattern:  /{citySlug}/add
    defaults: { _controller: CalderaCriticalmassSiteBundle:Ride:add }

caldera_criticalmass_ride_show:
    pattern:  /{citySlug}/{rideDate}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Ride:show }
    requirements:
        rideDate: "([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})"

caldera_criticalmass_desktop_ride_edit:
    pattern:  /{citySlug}/{rideDate}/edit
    defaults: { _controller: CalderaCriticalmassSiteBundle:Ride:edit }

caldera_criticalmass_ride_addestimate:
    pattern:  /{citySlug}/{rideDate}/addestimate
    defaults: { _controller: CalderaCriticalmassSiteBundle:Ride:addestimate }

