caldera_criticalmass_search_query:
    pattern:  /search/query
    defaults: { _controller: CalderaCriticalmassSiteBundle:Search:query }

caldera_criticalmass_search_prefetch:
    pattern:  /search/prefetch
    defaults: { _controller: CalderaCriticalmassSiteBundle:Search:prefetch }
