caldera_criticalmass_statistic_city:
    pattern: /{citySlug}/statistic
    defaults: { _controller: CalderaCriticalmassSiteBundle:Statistic:citystatistic }

caldera_criticalmass_statistic_facebook:
    pattern: /facebookstatistic
    defaults: { _controller: CalderaCriticalmassSiteBundle:Statistic:facebookstatistic }

caldera_criticalmass_statistic_overview:
    pattern: /statistic
    defaults: { _controller: CalderaCriticalmassSiteBundle:Statistic:overview }
