caldera_criticalmass_statistic_city:
    path: /{citySlug}/statistic
    defaults: { _controller: CalderaCriticalmassSiteBundle:Statistic:citystatistic }

caldera_criticalmass_statistic_facebook:
    path: /facebookstatistic
    defaults: { _controller: CalderaCriticalmassSiteBundle:Statistic:facebookstatistic }

caldera_criticalmass_statistic_overview:
    path: /statistic
    defaults: { _controller: CalderaCriticalmassSiteBundle:Statistic:overview }
