caldera_criticalmass_desktop_subride_add:
    pattern:  /add/{citySlug}/{rideDate}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:add }

caldera_criticalmass_desktop_subride_edit:
    pattern:  /edit/{subrideId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:edit }
    
caldera_criticalmass_subride_preparecopy:
    pattern:  /{citySlug}/{rideDate}/preparecopysubrides
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:preparecopy }
    
caldera_criticalmass_desktop_subride_copy:
    pattern:  /{citySlug}/{newDate}/copysubrides/{oldDate}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Subride:copy }