caldera_criticalmass_timeline_yearmonth:
    path:     /timeline/{year}/{month}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Timeline:yearmonth }
    requirements:
        year: "([0-9]{4,4})"
        month: "([0-9]{2,2})"