caldera_criticalmass_track_deleteconfirm:
    pattern:  /track/delete/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:delete }

caldera_criticalmass_track_toggle:
    pattern:  /track/toggle/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:toggle }

caldera_criticalmass_track_download:
    pattern:  /track/download/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:download }

caldera_criticalmass_track_gpxgenerate:
    pattern:  /track/generate/{rideId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:gpxgenerate }

caldera_criticalmass_track_list:
    pattern:  /track/list
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:list }

caldera_criticalmass_track_upload:
    pattern:  /{citySlug}/{rideDate}/addtrack
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:upload }

caldera_criticalmass_track_view:
    pattern:  /track/view/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:view }

caldera_criticalmass_track_range:
    pattern:  /track/range/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:range }

caldera_criticalmass_track_time:
    pattern:  /track/time/{trackId}
    defaults: { _controller: CalderaCriticalmassSiteBundle:Track:time }
