services:
    caldera.criticalmass.timeline.cached:
        class: AppBundle\Timeline\CachedTimeline
        arguments: [ '@doctrine', '@templating', '%timeline.ttl%' ]

    caldera.criticalmass.timeline:
        class: AppBundle\Timeline\Timeline
        arguments: [ '@doctrine', '@templating' ]