services:
    sonata.admin.heatmap:
        class: Caldera\CriticalmassStatisticBundle\Admin\HeatmapAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Statistik", label: "Heatmap" }
        arguments:
            - ~
            - Caldera\CriticalmassStatisticBundle\Entity\Heatmap
            - ~
        calls:
            - [ setTranslationDomain, [CalderaCriticalmassAdminBundle]]