caldera_criticalmass_statistic_index:
    pattern:  /statistic
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Statistic:index }

caldera_criticalmass_statistic_city_participants:
    pattern:  /statistic/city/participants/{citySlug}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Statistic:cityparticipants }

caldera_criticalmass_statistic_ride_participants:
    pattern:  /statistic/ride/participants/{year}/{month}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Statistic:rideparticipants, year: null, month: null }

caldera_criticalmass_statistic_ride_estimate:
    pattern:  /{citySlug}/{rideDate}/estimate
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Ride:estimate }

caldera_criticalmass_heatmap_homepage:
    pattern:  /heatmap/generate/{heatmapId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:generate }