caldera_criticalmass_statistic_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:index }

caldera_criticalmass_heatmap_homepage:
    pattern:  /heatmap/generate/{heatmapId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:generate }

caldera_criticalmass_statistic_track_index:
    pattern:  /track/list
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:index }
