caldera_criticalmass_statistic_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:index }

caldera_criticalmass_statistic_track_list:
    pattern:  /track/list
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:list }

caldera_criticalmass_statistic_track_upload:
    pattern:  /track/upload
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:upload }

caldera_criticalmass_statistic_track_setride:
    pattern:  /track/setride/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:setRide }

caldera_criticalmass_statistic_track_upload_failed:
    pattern:  /track/upload/failed
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:uploadFailed }

caldera_criticalmass_statistic_track_view:
    pattern:  /track/view/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:view }

caldera_criticalmass_statistic_ride_estimate:
    pattern:  /{citySlug}/{rideDate}/estimate
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Ride:estimate }

caldera_criticalmass_statistic_gpxgenerate:
    pattern: /track/generate/{rideId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:gpxgenerate }

caldera_criticalmass_heatmap_homepage:
    pattern:  /heatmap/generate/{heatmapId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:generate }

caldera_criticalmass_statistic_track_deleteconfirm:
    pattern:  /track/deleteconfirm/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:deleteconfirm }

caldera_criticalmass_statistic_track_toggle:
    pattern:  /track/toggle/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:toggle }

caldera_criticalmass_statistic_track_download:
    pattern:  /track/download/{trackId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:download }