caldera_criticalmass_statistic_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:index }

caldera_criticalmass_heatmap_homepage:
    pattern:  /heatmap/generate/{heatmapId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Default:generate }

caldera_criticalmass_statistic_track_list:
    pattern:  /track/list
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:list }

caldera_criticalmass_statistic_track_upload:
    pattern:  /track/upload
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:upload }

caldera_criticalmass_statistic_gpxgenerate:
    pattern: /track/generate/{rideId}
    defaults: { _controller: CalderaCriticalmassStatisticBundle:Track:gpxgenerate }
