parameters:
#    caldera_criticalmass_statistic.example.class: Caldera\CriticalmassStatisticBundle\Example

services:
#    caldera_criticalmass_statistic.example:
#        class: %caldera_criticalmass_statistic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
