criticalmass_gallery_homepage:
    path:     /hello
    defaults: { _controller: CriticalmassGalleryBundle:Default:index }

criticalmass_gallery_photos_add:
    pattern:  /photos/add
    defaults: { _controller: CriticalmassGalleryBundle:Photos:add }

criticalmass_gallery_photos_list:
    pattern:  /photos/list
    defaults: { _controller: CriticalmassGalleryBundle:Photos:list }

criticalmass_gallery_photos_edit:
    pattern: /photos/edit/{photoId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:edit }

criticalmass_gallery_photos_show:
    pattern: /photos/show/{photoId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:show }