criticalmass_gallery_photos/index:
    path:     /photos/index
    defaults: { _controller: CriticalmassGalleryBundle:Default:index }

criticalmass_gallery_photos_add:
    pattern:  /photos/add
    defaults: { _controller: CriticalmassGalleryBundle:Photos:add }

criticalmass_gallery_photos_add_city:
    pattern:  /photos/add/city/{cityId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:add }

criticalmass_gallery_photos_add_ride:
    pattern:  /photos/add/ride/{rideId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:add }

criticalmass_gallery_photos_list:
    pattern:  /photos/list
    defaults: { _controller: CriticalmassGalleryBundle:Photos:list }

criticalmass_gallery_photos_edit:
    pattern: /photos/edit/{photoId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:edit }

criticalmass_gallery_photos_show:
    pattern: /photos/show/{photoId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:show }

criticalmass_gallery_photos_delete:
    pattern: /photos/delete/{photoId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:delete }

criticalmass_gallery_photos_report:
    pattern: /photos/report/{photoId}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:report }

criticalmass_gallery_photos_change:
    pattern: /photos/change/{photoId}/{latitude}/{longitude}
    defaults: { _controller: CriticalmassGalleryBundle:Photos:change }