parameters:
#    caldera_criticalmass_admin.example.class: Caldera\CriticalmassAdminBundle\Example

services:
#    caldera_criticalmass_admin.example:
#        class: %caldera_criticalmass_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
