caldera_criticalmassphoto_photo_index:
    path:     /
    defaults: { _controller: CalderaCriticalmassPhotoBundle:Default:index }

caldera_criticalmassphoto_photo_list:
    path:     /{citySlug}/{rideDate}
    defaults: { _controller: CalderaCriticalmassPhotoBundle:Default:list }

caldera_criticalmassphoto_photo_show:
    path:     /{citySlug}/{rideDate}/{photoId}
    defaults: { _controller: CalderaCriticalmassPhotoBundle:Default:show }
