parameters:
#    caldera.example.class: Caldera\Bundle\CalderaBundle\Example

services:
    caldera.parser.multistep:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\MultiStepParser
        calls:
            - [ addStep, [ '@caldera.parser.multistep.link' ]]
            - [ addStep, [ '@caldera.parser.multistep.markdown' ]]
            - [ addStep, [ '@caldera.parser.multistep.anchor' ]]

    caldera.parser.multistep.markdown:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\Step\MarkdownParserStep
        arguments: [ '@markdown.parser' ]

    caldera.parser.multistep.link:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\Step\LinkParserStep

    caldera.parser.multistep.anchor:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\Step\AnchorParserStep

    caldera.user_provider:
        class: Caldera\Bundle\CalderaBundle\UserProvider\FOSUBUserProvider
        arguments: ["@fos_user.user_manager", {facebook: facebookId, strava: stravaId, runkeeper: runkeeperId}]

    caldera.manager.content_manager:
        class: Caldera\Bundle\CalderaBundle\Manager\ContentManager\ContentManager
        arguments: ['@doctrine']

    caldera.html_metadata:
        class: Caldera\Bundle\CalderaBundle\HtmlMetadata\Metadata

    caldera.view_storage:
        class: Caldera\Bundle\CalderaBundle\ViewStorage\ViewStorage
        arguments: ['@doctrine.cache.memcached']