parameters:
#    caldera.example.class: Caldera\Bundle\CalderaBundle\Example

services:
    caldera.parser.multistep:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\MultiStepParser
        calls:
            - [ addStep, [ '@caldera.parser.multistep.link' ]]
            - [ addStep, [ '@caldera.parser.multistep.markdown' ]]

    caldera.parser.multistep.markdown:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\Step\MarkdownParserStep
        arguments: [ '@markdown.parser' ]

    caldera.parser.multistep.link:
        class: Caldera\Bundle\CalderaBundle\Parser\MultiStepParser\Step\LinkParserStep

    caldera.user_provider:
        class: Caldera\Bundle\CalderaBundle\UserProvider\FOSUBUserProvider
        arguments: ["@fos_user.user_manager", {facebook: facebookId, strava: stravaId, runkeeper: runkeeperId}]
