caldera_criticalmass_rest_ride_list:
    path:     /ride/list
    defaults: { _controller: CalderaBundle:Api/Ride:list }

caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    defaults: { _controller: CalderaBundle:Api/City:show }

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/current
    defaults: { _controller: CalderaBundle:Api/Ride:showCurrent }

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/{rideDate}
    defaults: { _controller: CalderaBundle:Api/Ride:show }

