caldera_criticalmass_rest_ride_list:
    path:     /ride
    controller: App\Controller\Api\RideController::listAction
    methods:  [GET]

caldera_criticalmass_rest_city_list:
    path:     /city
    controller: App\Controller\Api\CityController::listAction
    methods:  [GET]

caldera_criticalmass_rest_photo_gallery:
    path:     /photo/gallery
    controller: App\Controller\Api\PhotoController::galleryAction
    methods:  [GET]

caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    controller: App\Controller\Api\CityController::showAction
    methods:  [GET]
    options:
        expose: true

caldera_criticalmass_rest_ride_show_current:
    path:     /{citySlug}/current
    controller: App\Controller\Api\RideController::showCurrentAction
    methods:  [GET]
    options:
        expose: true

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/{rideIdentifier}
    controller: App\Controller\Api\RideController::showAction
    methods:  [GET]
    options:
        expose: true

caldera_criticalmass_rest_estimate_create:
    path:     /estimate
    controller: App\Controller\Api\EstimateController::createAction
    methods:  [POST]
