caldera_criticalmass_rest_city_list:
    path:     /city
    controller: App\Controller\Api\CityController::listAction
    methods:  [GET]

caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    controller: App\Controller\Api\CityController::showAction
    methods:  [GET]
    options:
        expose: true