caldera_criticalmass_rest_track_ridelist:
    path:     /{citySlug}/{rideIdentifier}/listTracks
    controller: App\Controller\Api\TrackController::listRideTrackAction
    methods:  [GET]

caldera_criticalmass_rest_track_view:
    path:  /track/{trackId}
    controller: App\Controller\Api\TrackController::viewAction
    methods: [GET]

caldera_criticalmass_rest_track_list:
    path:  /track
    controller: App\Controller\Api\TrackController::listAction
    methods: [GET]

caldera_criticalmass_rest_ride_list:
    path:     /ride
    controller: App\Controller\Api\RideController::listAction
    methods:  [GET]

caldera_criticalmass_rest_city_list:
    path:     /city
    controller: App\Controller\Api\CityController::listAction
    methods:  [GET]

caldera_criticalmass_rest_photo_ridelist:
    path:     /{citySlug}/{rideIdentifier}/listPhotos
    controller: App\Controller\Api\PhotoController::listRidePhotosAction
    methods:  [GET]

caldera_criticalmass_rest_photo_list:
    path:     /photo
    controller: App\Controller\Api\PhotoController::listAction
    methods:  [GET]

caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    controller: App\Controller\Api\CityController::showAction
    methods:  [GET]
    options:
        expose: true

caldera_criticalmass_rest_ride_show_current:
    path:     /{citySlug}/current
    controller: App\Controller\Api\RideController::showCurrentAction
    methods:  [GET]
    options:
        expose: true

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/{rideIdentifier}
    controller: App\Controller\Api\RideController::showAction
    methods:  [GET]
    options:
        expose: true

caldera_criticalmass_rest_estimate_create:
    path:     /estimate
    controller: App\Controller\Api\EstimateController::createAction
    methods:  [POST]