caldera_criticalmass_rest_ride_list:
    path:     /ride
    controller: App\Controller\Api/Ride:list
    methods:  [GET]

caldera_criticalmass_rest_ride_list_deprecated:
    path:     /ride/list
    controller: App\Controller\Api/Ride:list
    methods:  [GET]

caldera_criticalmass_rest_city_list:
    path:     /city
    controller: App\Controller\Api/City:list
    methods:  [GET]

caldera_criticalmass_rest_city_list_deprecated:
    path:     /city/list
    controller: App\Controller\Api/City:list
    methods:  [GET]

caldera_criticalmass_rest_photo_gallery:
    path:     /photo/gallery
    controller: App\Controller\Api/Photo:gallery
    methods:  [GET]

caldera_criticalmass_rest_city_show:
    path:     /{citySlug
    controller: App\Controller\Api/City:show
    methods:  [GET]

caldera_criticalmass_rest_ride_show_current:
    path:     /{citySlug/current
    controller: App\Controller\Api/Ride:showCurrent
    methods:  [GET]

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug/{rideDate
    controller: App\Controller\Api/Ride:show
    methods:  [GET]

caldera_criticalmass_rest_estimate_create:
    path:     /estimate
    controller: App\Controller\Api/Estimate:create
    methods:  [POST]
