caldera_criticalmass_board_overview:
    path:  /boards/overview
    controller: App\Controller\Board:overview

caldera_criticalmass_board_listthreads:
    path:  /boards/{boardSlug
    controller: App\Controller\Board:listthreads

caldera_criticalmass_board_addthread:
    path:  /boards/{boardSlug/addthread
    controller: App\Controller\Board:addthread

caldera_criticalmass_board_viewthread:
    path:  /boards/{boardSlug/thread/{threadSlug
    controller: App\Controller\Board:viewthread

caldera_criticalmass_board_listcitythreads:
    path:  /{citySlug/listthreads
    controller: App\Controller\Board:listthreads

caldera_criticalmass_board_addcitythread:
    path:  /{citySlug/addthread
    controller: App\Controller\Board:addthread

caldera_criticalmass_board_viewcitythread:
    path:  /{citySlug/thread/{threadSlug
    controller: App\Controller\Board:viewthread
