caldera_criticalmass_city_show:
    path:  /{citySlug
    controller: App\Controller\City/City:show
    options:
        expose: true

caldera_criticalmass_city_listrides:
    path:  /{citySlug/list
    controller: App\Controller\City/City:listRides

caldera_criticalmass_city_missingstats:
    path:  /{citySlug/missingstats
    controller: App\Controller\City/City:missingStats

caldera_criticalmass_city_listgalleries:
    path:  /{citySlug/galleries
    controller: App\Controller\City/City:listGalleries

caldera_criticalmass_city_locations:
    path:  /{citySlug/locations
    controller: App\Controller\City/City:getlocations
