caldera_criticalmass_citycycle_list:
    path:  /{citySlug}/cycles/list
    controller: App\Controller\City\CityCycleController::listAction

caldera_criticalmass_citycycle_add:
    path:  /{citySlug}/cycles/add
    controller: App\Controller\City\CityCycleController::addAction

caldera_criticalmass_citycycle_edit:
    path:  /{citySlug}/cycles/{cycleId}/edit
    controller: App\Controller\City\CityCycleController::editAction

caldera_criticalmass_citycycle_disable:
    path:  /{citySlug}/cycles/{cycleId}/disable
    controller: App\Controller\City\CityCycleController::disableAction
