caldera_criticalmass_citycycle_list:
    path:  /{citySlug/cycles/list
    controller: App\Controller\City/CityCycle:list

caldera_criticalmass_citycycle_add:
    path:  /{citySlug/cycles/add
    controller: App\Controller\City/CityCycle:add

caldera_criticalmass_citycycle_edit:
    path:  /{citySlug/cycles/{cycleId/edit
    controller: App\Controller\City/CityCycle:edit

caldera_criticalmass_citycycle_disable:
    path:  /{citySlug/cycles/{cycleId/disable
    controller: App\Controller\City/CityCycle:disable
