caldera_criticalmass_heatmap_city:
    path:     /{citySlug}/heatmap
    controller: App\Controller\Heatmap\HeatmapController::cityAction

caldera_criticalmass_heatmap_user:
    path:     /{citySlug}/{rideIdentifier}/heatmap
    controller: App\Controller\Heatmap\HeatmapController::rideAction