caldera_criticalmass_help_index:
    path:     /help
    controller: App\Controller\Help:help

caldera_criticalmass_help_faq:
    path:     /faq
    controller: App\Controller\Help:faq

caldera_criticalmass_help_about:
    path:     /about
    controller: App\Controller\Help:about
