caldera_criticalmass_location_show:
    path:  /{citySlug}/location/{locationSlug}
    defaults: { _controller: App:Location:show }

caldera_criticalmass_location_ride:
    path:  /{citySlug}/{rideDate}/location
    defaults: { _controller: App:Location:ride }
