caldera_criticalmass_location_show:
    path:  /{citySlug/location/{locationSlug
    controller: App\Controller\Location:show

caldera_criticalmass_location_ride:
    path:  /{citySlug/{rideDate/location
    controller: App\Controller\Location:ride
