caldera_criticalmass_multipage_index:
    path: /
    controller: CalderaCriticalmassMobileBundle:MultiPage:main

caldera_criticalmass_multipage_slugindex:
    path: /{slug
    controller: CalderaCriticalmassMobileBundle:MultiPage:slugindex
