caldera_criticalmass_photo_user_list:
    path: /photos/list
    controller: App\Controller\Photo/PhotoManagement:list

caldera_criticalmass_photo_manage:
    path: /{citySlug/{rideDate/managephotos
    controller: App\Controller\Photo/PhotoManagement:manage

caldera_criticalmass_photo_place_single:
    path: /photo/{photoId/place
    controller: App\Controller\Photo/PhotoManagement:placeSingle

caldera_criticalmass_photo_rotate:
    path: /photo/{photoId/rotate
    controller: App\Controller\Photo/PhotoManagement:rotate

caldera_criticalmass_photo_toggle:
    path: /photo/{photoId/toggle
    controller: App\Controller\Photo/PhotoManagement:toggle

caldera_criticalmass_photo_featured:
    path: /photo/{photoId/featured
    controller: App\Controller\Photo/PhotoManagement:featuredPhoto

caldera_criticalmass_photo_delete:
    path: /managephotos/{photoId/delete
    controller: App\Controller\Photo/PhotoManagement:delete

caldera_criticalmass_photo_relocate:
    path: /{citySlug/{rideDate/relocatephotos
    controller: App\Controller\Photo/PhotoManagement:relocate

caldera_criticalmass_gallery_photos_rearrange:
    path: /{citySlug/{rideDate/gallery/rearrange
    controller: App\Controller\Photo/PhotoManagement:rearrange

caldera_criticalmass_photo_censor:
    path: /photo/{photoId/censor
    controller: App\Controller\Photo/PhotoManagement:censor

caldera_criticalmass_photo_censor_short:
    path: /photo/{photoId/censor
    controller: App\Controller\Photo/PhotoManagement:censor
    options:
        expose: true
