caldera_criticalmass_gallery_photos_upload_ride:
    path: /{citySlug/{rideDate/addphoto
    controller: App\Controller\Photo/PhotoUpload:upload
    requirements:
        rideDate: '([0-9]{4,4)\-([0-9]{1,2)\-([0-9]{1,2)'

caldera_criticalmass_photo_upload_event:
    path: /{citySlug/{eventSlug/addphoto
    controller: App\Controller\Photo/PhotoUpload:upload
