caldera_criticalmass_timeline_post_write:
    path:     /write
    controller: App\Controller\Post:write

caldera_criticalmass_timeline_post_write_ride:
    path:     /write/ride/{rideId
    controller: App\Controller\Post:writeRide

caldera_criticalmass_timeline_post_write_city:
    path:     /write/city/{cityId
    controller: App\Controller\Post:writeCity

caldera_criticalmass_timeline_post_write_photo:
    path:     /write/photo/{photoId
    controller: App\Controller\Post:writePhoto

caldera_criticalmass_timeline_post_write_thread:
    path:     /write/thread/{threadId
    controller: App\Controller\Post:writeThread
