caldera_criticalmass_region_world:
    path:     /world
    controller: App\Controller\RegionController::indexAction

caldera_criticalmass_region_world_region_1:
    path:     /world/{slug1}
    controller: App\Controller\RegionController::indexAction

caldera_criticalmass_region_world_region_2:
    path:     /world/{slug1}/{slug2}
    controller: App\Controller\RegionController::indexAction

caldera_criticalmass_region_world_region_3:
    path:     /world/{slug1}/{slug2}/{slug3}
    controller: App\Controller\RegionController::indexAction
