caldera_criticalmass_ride_add:
    path:  /{citySlug}/add-ride
    controller: App\Controller\Ride\RideManagementController::addAction

caldera_criticalmass_ride_edit:
    path:  /{citySlug}/{rideDate}/edit
    controller: App\Controller\Ride\RideManagementController::editAction

caldera_criticalmass_ride_socialpreview:
    path:  /{citySlug}/{rideDate}/socialpreview
    controller: App\Controller\Ride\RideManagementController::socialPreviewAction
