caldera_criticalmass_ride_addestimate:
    path:  /{citySlug/{rideDate/addestimate
    controller: App\Controller\Ride/RideEstimate:addestimate

caldera_criticalmass_ride_addestimate_anonymous:
    path:  /{citySlug/{rideDate/anonymousestimate
    controller: App\Controller\Ride/RideEstimate:anonymousestimate
