caldera_criticalmass_search_query:
    path:  /search/query
    controller: App\Controller\SearchController::queryAction

caldera_criticalmass_search_prefetch:
    path:  /search/prefetch
    controller: App\Controller\SearchController::prefetchAction
    options:
        expose: true
