caldera_criticalmass_search_query:
    path:  /search/query
    controller: App\Controller\Search:query

caldera_criticalmass_search_prefetch:
    path:  /search/prefetch
    controller: App\Controller\Search:prefetch
    options:
        expose: true
