criticalmass_socialnetwork_city_list:
    path:  /{citySlug/socialnetwork/list
    controller: App\Controller\SocialNetwork/SocialNetworkList:listCity

criticalmass_socialnetwork_ride_list:
    path:  /{citySlug/{rideDate/socialnetwork/list
    controller: App\Controller\SocialNetwork/SocialNetworkList:listRide
    requirements:
        rideDate: '([0-9]{4,4)\-([0-9]{2,2)\-([0-9]{1,2)'

criticalmass_socialnetwork_city_add:
    path:  /{citySlug/socialnetwork/add
    controller: App\Controller\SocialNetwork/SocialNetwork:add

criticalmass_socialnetwork_ride_add:
    path:  /{citySlug/{rideDate/socialnetwork/add
    controller: App\Controller\SocialNetwork/SocialNetwork:add
    requirements:
        rideDate: '([0-9]{4,4)\-([0-9]{2,2)\-([0-9]{1,2)'

criticalmass_socialnetwork_disable:
    path:  /socialnetwork/{profileId/disable
    controller: App\Controller\SocialNetwork/SocialNetwork:disable
