criticalmass_socialnetwork_city_list:
    path:  /{citySlug}/socialnetwork/list
    controller: App\Controller\SocialNetwork\SocialNetworkListController::listCityAction

criticalmass_socialnetwork_ride_list:
    path:  /{citySlug}/{rideDate}/socialnetwork/list
    controller: App\Controller\SocialNetwork\SocialNetworkListController::listRideAction
    requirements:
        rideDate: '([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})'

criticalmass_socialnetwork_city_add:
    path:  /{citySlug}/socialnetwork/add
    controller: App\Controller\SocialNetwork\SocialNetworkController::addAction

criticalmass_socialnetwork_ride_add:
    path:  /{citySlug}/{rideDate/socialnetwork/add
    controller: App\Controller\SocialNetwork\SocialNetworkController::addAction
    requirements:
        rideDate: '([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})'

criticalmass_socialnetwork_disable:
    path:  /socialnetwork/{profileId}/disable
    controller: App\Controller\SocialNetwork\SocialNetworkController::disableAction
