caldera_criticalmass_statistic_city:
    path: /{citySlug/statistic
    controller: App\Controller\Statistic/Statistic:citystatistic

caldera_criticalmass_statistic_overview:
    path: /statistic
    controller: App\Controller\Statistic/Statistic:overview

caldera_criticalmass_statistic_ride_month:
    path: /statistic/{year/{month
    controller: App\Controller\Statistic/MonthlyStats:listRides

caldera_criticalmass_statistic_topten:
    path: /statistic/top
    controller: App\Controller\Statistic/TopStats:topStats
