caldera_criticalmass_strava_auth:
    path:  /{citySlug}/{rideDate}/stravaauth
    controller: App\Controller\Track\StravaController::authAction

caldera_criticalmass_strava_token:
    path:  /{citySlug}/{rideDate}/stravatoken
    controller: App\Controller\Track\StravaController::tokenAction

caldera_criticalmass_strava_list:
    path:  /{citySlug}/{rideDate}/stravalist
    controller: App\Controller\Track\StravaController::listridesAction

caldera_criticalmass_strava_import:
    path:  /{citySlug}/{rideDate}/stravaimport
    controller: App\Controller\Track\StravaController::importAction
