caldera_criticalmass_strava_auth:
    path:  /{citySlug}/{rideIdentifier}/stravaauth
    controller: App\Controller\StravaController::authAction

caldera_criticalmass_strava_token:
    path:  /{citySlug}/{rideIdentifier}/stravatoken
    controller: App\Controller\StravaController::tokenAction

caldera_criticalmass_strava_list:
    path:  /{citySlug}/{rideIdentifier}/stravalist
    controller: App\Controller\StravaController::listridesAction

caldera_criticalmass_strava_import:
    path:  /{citySlug}/{rideIdentifier}/stravaimport
    controller: App\Controller\StravaController::importAction
