caldera_criticalmass_timelapse_homepage:
    path:     /{citySlug/{rideDate/timelapse
    controller: App\Controller\Ride/Timelapse:show

caldera_criticalmass_timelapse_load:
    path:     /{citySlug/{rideDate/timelapse/load/{trackId
    controller: App\Controller\Ride/Timelapse:loadtrack
    options:
        expose: true
