caldera_criticalmass_timeline_yearmonth:
    path:     /timeline/{year}/{month}
    controller: App\Controller\TimelineController::yearmonthAction
    requirements:
        year: "([0-9]{4,4})"
        month: "([0-9]{2,2})"

caldera_criticalmass_timeline_index:
    path:     /timeline
    controller: App\Controller\TimelineController::indexAction
