caldera_criticalmass_track_delete:
    path:  /track/delete/{trackId
    controller: App\Controller\Track/TrackManagement:delete
    options:
        expose: true

caldera_criticalmass_track_toggle:
    path:  /track/toggle/{trackId
    controller: App\Controller\Track/TrackManagement:toggle

caldera_criticalmass_track_download:
    path:  /track/download/{trackId
    controller: App\Controller\Track/TrackManagement:download

caldera_criticalmass_track_gpxgenerate:
    path:  /track/generate/{rideId
    controller: App\Controller\Track/TrackManagement:gpxgenerate

caldera_criticalmass_track_list:
    path:  /track/list
    controller: App\Controller\Track/TrackManagement:list

caldera_criticalmass_track_upload:
    path:  /{citySlug/{rideDate/addtrack
    controller: App\Controller\Track/TrackUpload:upload

caldera_criticalmass_track_view:
    path:  /track/view/{trackId
    controller: App\Controller\Track/Track:view

caldera_criticalmass_track_range:
    path:  /track/range/{trackId
    controller: App\Controller\Track/TrackRange:range

caldera_criticalmass_track_time:
    path:  /track/time/{trackId
    controller: App\Controller\Track/TrackTime:time

caldera_criticalmass_track_draw:
    path:  /{citySlug/{rideDate/drawtrack
    controller: App\Controller\Track/TrackDraw:draw

caldera_criticalmass_track_edit:
    path:  /track/edit/{trackId
    controller: App\Controller\Track/TrackManagement:edit
