parameters:
#    caldera_criticalmass_photo.example.class: Caldera\Bundle\CriticalmassPhotoBundle\Example

services:
#    caldera_criticalmass_photo.example:
#        class: %caldera_criticalmass_photo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
